  MetadataConfigCreateRequest:
    type: "object"
    description: "Object used to create a Metadata Configuration in Datahub"
    required: ["data"]
    properties:
      data:
        type: "object"
        required: ["type", "attributes"]
        properties:
          type: 
            type: "string"
            enum: [metadataConfigs]
          id:
            type: "string"
          attributes:
            type: "object"
            required: ["startPoint", "endPoint", "midPoints"]
            properties:
              startPoint:
                description: "The first point of a Logical Map"
                type: "string"
              endPoint:
                description: "The last point of a Logical Map"
                type: "string"
              midPoints: 
                description: "The points between the startPoint and endPoint of a logical map"
                type: "array"
                items:
                  type: "string"
                    
  MetadataConfigUpdateRequest:
    type: "object"
    description: "Object used to update a Metadata Configuration in Datahub"
    required: ["data"]
    properties:
      data:
        type: "object"
        required: ["type", "id", "attributes"]
        properties:
          type: 
            type: "string"
            enum: [metadataConfigs]
          id:
            type: "string"
          attributes:
            type: "object"
            required: ["_rev"]
            properties:
              _rev:
                type: "string"
                description: "Value used to ensure updates to this object are handled in order."
              startPoint:
                description: "The first point of a Logical Map"
                type: "string"
              endPoint:
                description: "The last point of a Logical Map"
                type: "string"
              midPoints: 
                description: "The points between the startPoint and endPoint of a logical map"
                type: "array"
                items:
                  type: "string"
            
             
  MetadataConfigListResponse:
    type: "object"
    description: "Metadata Configuration response including one or more values"
    required: ["data"]
    properties:
      data:
        type: "array"
        items:
          $ref: '#/definitions/MetadataConfig'

  MetadataConfigResponse:
    type: "object"
    description: "A single object Metadata Configuration response from Datahub"
    required: ["data"]
    properties:
      data:
        $ref: '#/definitions/MetadataConfig'

  MetadataConfig:
    type: "object"
    required: ["type", "id", "attributes"]
    properties:
      type: 
        type: "string"
        enum: [metadataConfigs]
      id:
        type: "string"
      attributes:
        type: "object"
        required: ["_id", "_rev", "tenantId", "dataType", "startPoint", "endPoint", "midPoints", "createdTimestamp", "lastModifiedTimestamp"]
        properties:
          tenantId:
            type: "string"
            description: "Unique identifier of the Tenant in Datahub"
          _id:
            type: "string"
          _rev:
            type: "string"
            description: "Value used to ensure updates to this object are handled in order."
          datatype:
            description: "Name used to identify this type of record in Datahub"
            type: "string"
          startPoint:
            description: "The first point of a Logical Map"
            type: "string"
          endPoint:
            description: "The last point of a Logical Map"
            type: "string"
          midPoints: 
            description: "The points between the startPoint and endPoint of a logical map"
            type: "array"
            items:
              type: "string"
          createdTimestamp:
            type: "integer"
            description: "Time since epoch at which this object was instantiated."
          lastModifiedTimestamp:
            type: "integer"
            description: "Time since epoch at which this object was last altered."
