  /v2/report-schedule-configs:
    post:
      summary: Create a report schedule configuration for a Tenant.
      operationId: CreateReportScheduleConfigV2
      consumes:
        - application/vnd.api+json
      produces:
        - application/vnd.api+json
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/ReportScheduleConfigResponse'
        '400':
          description: "Request data does not pass validation"
          schema:
            type: string
        '403':
          description: "Requestor does not have authorization to perform this action"
          schema:
            type: string
        '409':
          description: "The Report Schedule Configuration is already provisioned"
          schema:
            type: string
        '500':
          description: "Unexpected error processing request"
          schema:
            type: string
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ReportScheduleConfigCreateRequest'
      tags:
        - TenantProvisioningServiceV2
    get:
      summary: Retrieve all report schedule configs for the specified Tenant.
      operationId: GetAllReportScheduleConfigsV2
      produces:
        - application/vnd.api+json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ReportScheduleConfigListResponse'
        '403':
          description: "Requestor does not have authorization to perform this action"
          schema:
            type: string
        '404':
          description: "No Report Schedule Configurations are provisioned"
          schema:
            type: string
        '500':
          description: "Unexpected error processing request"
          schema:
            type: string
      tags:
        - TenantProvisioningServiceV2
  /v2/report-schedule-configs/{configId}:
    get:
      summary: Retrieve a report schedule configuration for a Tenant by configuration Id.
      operationId: GetReportScheduleConfigV2
      produces:
        - application/vnd.api+json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ReportScheduleConfigResponse'
        '403':
          description: "Requestor does not have authorization to perform this action"
          schema:
            type: string
        '404':
          description: "The requested Report Schedule Configuration is not provisioned"
          schema:
            type: string
        '500':
          description: "Unexpected error processing request"
          schema:
            type: string
      parameters:
        - name: configId
          in: path
          required: true
          type: string
      tags:
        - TenantProvisioningServiceV2
    patch:
      summary: Update a Report Schedule Configuration for a Tenant.
      operationId: UpdateReportScheduleConfigV2
      produces:
        - application/vnd.api+json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ReportScheduleConfigResponse'
        '400':
          description: "Request data does not pass validation"
          schema:
            type: string
        '403':
          description: "Requestor does not have authorization to perform this action"
          schema:
            type: string
        '404':
          description: "Requested Report Schedule Configuration is not provisioned"
          schema:
            type: string
        '409':
          description: "Incorrect revision provided for this update request"
          schema:
            type: string
        '500':
          description: "Unexpected error processing request"
          schema:
            type: string
      parameters:
        - name: configId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ReportScheduleConfigUpdateRequest'
      tags:
        - TenantProvisioningServiceV2
    delete:
      summary: Delete a report schedule configuration for a Tenant by configuration Id.
      operationId: DeleteReportScheduleConfigV2
      produces:
        - application/vnd.api+json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ReportScheduleConfigResponse'
        '403':
          description: "Requestor does not have authorization to perform this action"
          schema:
            type: string
        '404':
          description: "Requested Report Schedule Configuration is not provisioned"
          schema:
            type: string
        '500':
          description: "Unexpected error processing request"
          schema:
            type: string
      parameters:
        - name: configId
          in: path
          required: true
          type: string
      tags:
        - TenantProvisioningServiceV2
    
