// Code generated by go-swagger; DO NOT EDIT.

package swagmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MetricBaselineUpdateHourRequest Object used to update a single Metric Baseline for a Monitored Object in Datahub
// swagger:model MetricBaselineUpdateHourRequest
type MetricBaselineUpdateHourRequest struct {

	// data
	// Required: true
	Data *MetricBaselineUpdateHourRequestData `json:"data"`
}

// Validate validates this metric baseline update hour request
func (m *MetricBaselineUpdateHourRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetricBaselineUpdateHourRequest) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MetricBaselineUpdateHourRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricBaselineUpdateHourRequest) UnmarshalBinary(b []byte) error {
	var res MetricBaselineUpdateHourRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// MetricBaselineUpdateHourRequestData metric baseline update hour request data
// swagger:model MetricBaselineUpdateHourRequestData
type MetricBaselineUpdateHourRequestData struct {

	// attributes
	// Required: true
	Attributes *MetricBaselineData `json:"attributes"`

	// id
	// Required: true
	ID *string `json:"id"`

	// type
	// Required: true
	// Enum: [metricBaselineHourUpdate]
	Type *string `json:"type"`
}

// Validate validates this metric baseline update hour request data
func (m *MetricBaselineUpdateHourRequestData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttributes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetricBaselineUpdateHourRequestData) validateAttributes(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"attributes", "body", m.Attributes); err != nil {
		return err
	}

	if m.Attributes != nil {
		if err := m.Attributes.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data" + "." + "attributes")
			}
			return err
		}
	}

	return nil
}

func (m *MetricBaselineUpdateHourRequestData) validateID(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

var metricBaselineUpdateHourRequestDataTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["metricBaselineHourUpdate"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		metricBaselineUpdateHourRequestDataTypeTypePropEnum = append(metricBaselineUpdateHourRequestDataTypeTypePropEnum, v)
	}
}

const (

	// MetricBaselineUpdateHourRequestDataTypeMetricBaselineHourUpdate captures enum value "metricBaselineHourUpdate"
	MetricBaselineUpdateHourRequestDataTypeMetricBaselineHourUpdate string = "metricBaselineHourUpdate"
)

// prop value enum
func (m *MetricBaselineUpdateHourRequestData) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, metricBaselineUpdateHourRequestDataTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *MetricBaselineUpdateHourRequestData) validateType(formats strfmt.Registry) error {

	if err := validate.Required("data"+"."+"type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("data"+"."+"type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MetricBaselineUpdateHourRequestData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricBaselineUpdateHourRequestData) UnmarshalBinary(b []byte) error {
	var res MetricBaselineUpdateHourRequestData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
