// Code generated by go-swagger; DO NOT EDIT.

package swagmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MetricBucketObject metric bucket object
// swagger:model MetricBucketObject
type MetricBucketObject struct {

	// index
	Index string `json:"index,omitempty"`

	// lower
	Lower float32 `json:"lower,omitempty"`

	// upper
	Upper float32 `json:"upper,omitempty"`
}

// Validate validates this metric bucket object
func (m *MetricBucketObject) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricBucketObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricBucketObject) UnmarshalBinary(b []byte) error {
	var res MetricBucketObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
