// Code generated by go-swagger; DO NOT EDIT.

package swagmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TenantThresholdProfileVendorMapVendorMap tenant threshold profile vendor map vendor map
// swagger:model tenantThresholdProfileVendorMapVendorMap
type TenantThresholdProfileVendorMapVendorMap map[string]TenantThresholdProfileMetric

// Validate validates this tenant threshold profile vendor map vendor map
func (m TenantThresholdProfileVendorMapVendorMap) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("", "body", TenantThresholdProfileVendorMapVendorMap(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
