// Code generated by go-swagger; DO NOT EDIT.

package swagmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TenantThresholdProfileMonitoredObjectTypeMapMetricMapDirectionMapEventMap tenant threshold profile monitored object type map metric map direction map event map
// swagger:model TenantThresholdProfileMonitoredObjectTypeMapMetricMapDirectionMapEventMap
type TenantThresholdProfileMonitoredObjectTypeMapMetricMapDirectionMapEventMap struct {

	// event map
	EventMap TenantThresholdProfileMonitoredObjectTypeMapMetricMapDirectionMapEventMapEventMap `json:"eventMap,omitempty"`
}

// Validate validates this tenant threshold profile monitored object type map metric map direction map event map
func (m *TenantThresholdProfileMonitoredObjectTypeMapMetricMapDirectionMapEventMap) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventMap(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TenantThresholdProfileMonitoredObjectTypeMapMetricMapDirectionMapEventMap) validateEventMap(formats strfmt.Registry) error {

	if swag.IsZero(m.EventMap) { // not required
		return nil
	}

	if err := m.EventMap.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("eventMap")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TenantThresholdProfileMonitoredObjectTypeMapMetricMapDirectionMapEventMap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TenantThresholdProfileMonitoredObjectTypeMapMetricMapDirectionMapEventMap) UnmarshalBinary(b []byte) error {
	var res TenantThresholdProfileMonitoredObjectTypeMapMetricMapDirectionMapEventMap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
