// Code generated by go-swagger; DO NOT EDIT.

package admin_provisioning_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	swagmodels "github.com/accedian/adh-gather/swagmodels"
)

// GetValidTypesOKCode is the HTTP code returned for type GetValidTypesOK
const GetValidTypesOKCode int = 200

/*GetValidTypesOK get valid types o k

swagger:response getValidTypesOK
*/
type GetValidTypesOK struct {

	/*
	  In: Body
	*/
	Payload *swagmodels.JSONAPIValidTypes `json:"body,omitempty"`
}

// NewGetValidTypesOK creates GetValidTypesOK with default headers values
func NewGetValidTypesOK() *GetValidTypesOK {

	return &GetValidTypesOK{}
}

// WithPayload adds the payload to the get valid types o k response
func (o *GetValidTypesOK) WithPayload(payload *swagmodels.JSONAPIValidTypes) *GetValidTypesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get valid types o k response
func (o *GetValidTypesOK) SetPayload(payload *swagmodels.JSONAPIValidTypes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetValidTypesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetValidTypesForbiddenCode is the HTTP code returned for type GetValidTypesForbidden
const GetValidTypesForbiddenCode int = 403

/*GetValidTypesForbidden Requestor does not have authorization to perform this action

swagger:response getValidTypesForbidden
*/
type GetValidTypesForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetValidTypesForbidden creates GetValidTypesForbidden with default headers values
func NewGetValidTypesForbidden() *GetValidTypesForbidden {

	return &GetValidTypesForbidden{}
}

// WithPayload adds the payload to the get valid types forbidden response
func (o *GetValidTypesForbidden) WithPayload(payload string) *GetValidTypesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get valid types forbidden response
func (o *GetValidTypesForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetValidTypesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetValidTypesInternalServerErrorCode is the HTTP code returned for type GetValidTypesInternalServerError
const GetValidTypesInternalServerErrorCode int = 500

/*GetValidTypesInternalServerError Unexpected error processing request

swagger:response getValidTypesInternalServerError
*/
type GetValidTypesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetValidTypesInternalServerError creates GetValidTypesInternalServerError with default headers values
func NewGetValidTypesInternalServerError() *GetValidTypesInternalServerError {

	return &GetValidTypesInternalServerError{}
}

// WithPayload adds the payload to the get valid types internal server error response
func (o *GetValidTypesInternalServerError) WithPayload(payload string) *GetValidTypesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get valid types internal server error response
func (o *GetValidTypesInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetValidTypesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
