// Code generated by go-swagger; DO NOT EDIT.

package admin_provisioning_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllAdminUsersHandlerFunc turns a function with the right signature into a get all admin users handler
type GetAllAdminUsersHandlerFunc func(GetAllAdminUsersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllAdminUsersHandlerFunc) Handle(params GetAllAdminUsersParams) middleware.Responder {
	return fn(params)
}

// GetAllAdminUsersHandler interface for that can handle valid get all admin users params
type GetAllAdminUsersHandler interface {
	Handle(GetAllAdminUsersParams) middleware.Responder
}

// NewGetAllAdminUsers creates a new http.Handler for the get all admin users operation
func NewGetAllAdminUsers(ctx *middleware.Context, handler GetAllAdminUsersHandler) *GetAllAdminUsers {
	return &GetAllAdminUsers{Context: ctx, Handler: handler}
}

/*GetAllAdminUsers swagger:route GET /v1/admin-user-list AdminProvisioningService getAllAdminUsers

Retrieve all Administrative Users.

*/
type GetAllAdminUsers struct {
	Context *middleware.Context
	Handler GetAllAdminUsersHandler
}

func (o *GetAllAdminUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllAdminUsersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
