// Code generated by go-swagger; DO NOT EDIT.

package admin_provisioning_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetIngestionDictionaryHandlerFunc turns a function with the right signature into a get ingestion dictionary handler
type GetIngestionDictionaryHandlerFunc func(GetIngestionDictionaryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIngestionDictionaryHandlerFunc) Handle(params GetIngestionDictionaryParams) middleware.Responder {
	return fn(params)
}

// GetIngestionDictionaryHandler interface for that can handle valid get ingestion dictionary params
type GetIngestionDictionaryHandler interface {
	Handle(GetIngestionDictionaryParams) middleware.Responder
}

// NewGetIngestionDictionary creates a new http.Handler for the get ingestion dictionary operation
func NewGetIngestionDictionary(ctx *middleware.Context, handler GetIngestionDictionaryHandler) *GetIngestionDictionary {
	return &GetIngestionDictionary{Context: ctx, Handler: handler}
}

/*GetIngestionDictionary swagger:route GET /v1/ingestion-dictionaries AdminProvisioningService getIngestionDictionary

Retrieve an Ingestion Dictionary.

*/
type GetIngestionDictionary struct {
	Context *middleware.Context
	Handler GetIngestionDictionaryHandler
}

func (o *GetIngestionDictionary) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetIngestionDictionaryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
