// Code generated by go-swagger; DO NOT EDIT.

package admin_provisioning_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	swagmodels "github.com/accedian/adh-gather/swagmodels"
)

// GetTenantOKCode is the HTTP code returned for type GetTenantOK
const GetTenantOKCode int = 200

/*GetTenantOK get tenant o k

swagger:response getTenantOK
*/
type GetTenantOK struct {

	/*
	  In: Body
	*/
	Payload *swagmodels.JSONAPITenant `json:"body,omitempty"`
}

// NewGetTenantOK creates GetTenantOK with default headers values
func NewGetTenantOK() *GetTenantOK {

	return &GetTenantOK{}
}

// WithPayload adds the payload to the get tenant o k response
func (o *GetTenantOK) WithPayload(payload *swagmodels.JSONAPITenant) *GetTenantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tenant o k response
func (o *GetTenantOK) SetPayload(payload *swagmodels.JSONAPITenant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTenantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTenantForbiddenCode is the HTTP code returned for type GetTenantForbidden
const GetTenantForbiddenCode int = 403

/*GetTenantForbidden Requestor does not have authorization to perform this action

swagger:response getTenantForbidden
*/
type GetTenantForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTenantForbidden creates GetTenantForbidden with default headers values
func NewGetTenantForbidden() *GetTenantForbidden {

	return &GetTenantForbidden{}
}

// WithPayload adds the payload to the get tenant forbidden response
func (o *GetTenantForbidden) WithPayload(payload string) *GetTenantForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tenant forbidden response
func (o *GetTenantForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTenantForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetTenantInternalServerErrorCode is the HTTP code returned for type GetTenantInternalServerError
const GetTenantInternalServerErrorCode int = 500

/*GetTenantInternalServerError Unexpected error processing request

swagger:response getTenantInternalServerError
*/
type GetTenantInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTenantInternalServerError creates GetTenantInternalServerError with default headers values
func NewGetTenantInternalServerError() *GetTenantInternalServerError {

	return &GetTenantInternalServerError{}
}

// WithPayload adds the payload to the get tenant internal server error response
func (o *GetTenantInternalServerError) WithPayload(payload string) *GetTenantInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tenant internal server error response
func (o *GetTenantInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTenantInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
