// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BulkUpdateMonitoredObjectsV2HandlerFunc turns a function with the right signature into a bulk update monitored objects v2 handler
type BulkUpdateMonitoredObjectsV2HandlerFunc func(BulkUpdateMonitoredObjectsV2Params) middleware.Responder

// Handle executing the request and returning a response
func (fn BulkUpdateMonitoredObjectsV2HandlerFunc) Handle(params BulkUpdateMonitoredObjectsV2Params) middleware.Responder {
	return fn(params)
}

// BulkUpdateMonitoredObjectsV2Handler interface for that can handle valid bulk update monitored objects v2 params
type BulkUpdateMonitoredObjectsV2Handler interface {
	Handle(BulkUpdateMonitoredObjectsV2Params) middleware.Responder
}

// NewBulkUpdateMonitoredObjectsV2 creates a new http.Handler for the bulk update monitored objects v2 operation
func NewBulkUpdateMonitoredObjectsV2(ctx *middleware.Context, handler BulkUpdateMonitoredObjectsV2Handler) *BulkUpdateMonitoredObjectsV2 {
	return &BulkUpdateMonitoredObjectsV2{Context: ctx, Handler: handler}
}

/*BulkUpdateMonitoredObjectsV2 swagger:route PUT /v2/bulk/insert/monitored-objects TenantProvisioningServiceV2 bulkUpdateMonitoredObjectsV2

Update one or more Monitored Objects in a single API request. Note that this is a PUT operation for each Monitored Object. This means that all properties must be explicitly provided

*/
type BulkUpdateMonitoredObjectsV2 struct {
	Context *middleware.Context
	Handler BulkUpdateMonitoredObjectsV2Handler
}

func (o *BulkUpdateMonitoredObjectsV2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBulkUpdateMonitoredObjectsV2Params()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
