// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	swagmodels "github.com/accedian/adh-gather/swagmodels"
)

// CreateConnectorConfigV2CreatedCode is the HTTP code returned for type CreateConnectorConfigV2Created
const CreateConnectorConfigV2CreatedCode int = 201

/*CreateConnectorConfigV2Created create connector config v2 created

swagger:response createConnectorConfigV2Created
*/
type CreateConnectorConfigV2Created struct {

	/*
	  In: Body
	*/
	Payload *swagmodels.ConnectorConfigResponse `json:"body,omitempty"`
}

// NewCreateConnectorConfigV2Created creates CreateConnectorConfigV2Created with default headers values
func NewCreateConnectorConfigV2Created() *CreateConnectorConfigV2Created {

	return &CreateConnectorConfigV2Created{}
}

// WithPayload adds the payload to the create connector config v2 created response
func (o *CreateConnectorConfigV2Created) WithPayload(payload *swagmodels.ConnectorConfigResponse) *CreateConnectorConfigV2Created {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create connector config v2 created response
func (o *CreateConnectorConfigV2Created) SetPayload(payload *swagmodels.ConnectorConfigResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateConnectorConfigV2Created) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateConnectorConfigV2BadRequestCode is the HTTP code returned for type CreateConnectorConfigV2BadRequest
const CreateConnectorConfigV2BadRequestCode int = 400

/*CreateConnectorConfigV2BadRequest Request data does not pass validation

swagger:response createConnectorConfigV2BadRequest
*/
type CreateConnectorConfigV2BadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateConnectorConfigV2BadRequest creates CreateConnectorConfigV2BadRequest with default headers values
func NewCreateConnectorConfigV2BadRequest() *CreateConnectorConfigV2BadRequest {

	return &CreateConnectorConfigV2BadRequest{}
}

// WithPayload adds the payload to the create connector config v2 bad request response
func (o *CreateConnectorConfigV2BadRequest) WithPayload(payload string) *CreateConnectorConfigV2BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create connector config v2 bad request response
func (o *CreateConnectorConfigV2BadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateConnectorConfigV2BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// CreateConnectorConfigV2ForbiddenCode is the HTTP code returned for type CreateConnectorConfigV2Forbidden
const CreateConnectorConfigV2ForbiddenCode int = 403

/*CreateConnectorConfigV2Forbidden Requestor does not have authorization to perform this action

swagger:response createConnectorConfigV2Forbidden
*/
type CreateConnectorConfigV2Forbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateConnectorConfigV2Forbidden creates CreateConnectorConfigV2Forbidden with default headers values
func NewCreateConnectorConfigV2Forbidden() *CreateConnectorConfigV2Forbidden {

	return &CreateConnectorConfigV2Forbidden{}
}

// WithPayload adds the payload to the create connector config v2 forbidden response
func (o *CreateConnectorConfigV2Forbidden) WithPayload(payload string) *CreateConnectorConfigV2Forbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create connector config v2 forbidden response
func (o *CreateConnectorConfigV2Forbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateConnectorConfigV2Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// CreateConnectorConfigV2ConflictCode is the HTTP code returned for type CreateConnectorConfigV2Conflict
const CreateConnectorConfigV2ConflictCode int = 409

/*CreateConnectorConfigV2Conflict The Connector being provisioned already exists

swagger:response createConnectorConfigV2Conflict
*/
type CreateConnectorConfigV2Conflict struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateConnectorConfigV2Conflict creates CreateConnectorConfigV2Conflict with default headers values
func NewCreateConnectorConfigV2Conflict() *CreateConnectorConfigV2Conflict {

	return &CreateConnectorConfigV2Conflict{}
}

// WithPayload adds the payload to the create connector config v2 conflict response
func (o *CreateConnectorConfigV2Conflict) WithPayload(payload string) *CreateConnectorConfigV2Conflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create connector config v2 conflict response
func (o *CreateConnectorConfigV2Conflict) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateConnectorConfigV2Conflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// CreateConnectorConfigV2InternalServerErrorCode is the HTTP code returned for type CreateConnectorConfigV2InternalServerError
const CreateConnectorConfigV2InternalServerErrorCode int = 500

/*CreateConnectorConfigV2InternalServerError Unexpected error processing request

swagger:response createConnectorConfigV2InternalServerError
*/
type CreateConnectorConfigV2InternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateConnectorConfigV2InternalServerError creates CreateConnectorConfigV2InternalServerError with default headers values
func NewCreateConnectorConfigV2InternalServerError() *CreateConnectorConfigV2InternalServerError {

	return &CreateConnectorConfigV2InternalServerError{}
}

// WithPayload adds the payload to the create connector config v2 internal server error response
func (o *CreateConnectorConfigV2InternalServerError) WithPayload(payload string) *CreateConnectorConfigV2InternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create connector config v2 internal server error response
func (o *CreateConnectorConfigV2InternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateConnectorConfigV2InternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
