// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDashboardV2Params creates a new DeleteDashboardV2Params object
// no default values defined in spec.
func NewDeleteDashboardV2Params() DeleteDashboardV2Params {

	return DeleteDashboardV2Params{}
}

// DeleteDashboardV2Params contains all the bound params for the delete dashboard v2 operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteDashboardV2
type DeleteDashboardV2Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	DashboardID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteDashboardV2Params() beforehand.
func (o *DeleteDashboardV2Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rDashboardID, rhkDashboardID, _ := route.Params.GetOK("dashboardId")
	if err := o.bindDashboardID(rDashboardID, rhkDashboardID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDashboardID binds and validates parameter DashboardID from path.
func (o *DeleteDashboardV2Params) bindDashboardID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.DashboardID = raw

	return nil
}
