// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewDeleteDataCleaningProfileParams creates a new DeleteDataCleaningProfileParams object
// no default values defined in spec.
func NewDeleteDataCleaningProfileParams() DeleteDataCleaningProfileParams {

	return DeleteDataCleaningProfileParams{}
}

// DeleteDataCleaningProfileParams contains all the bound params for the delete data cleaning profile operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteDataCleaningProfile
type DeleteDataCleaningProfileParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteDataCleaningProfileParams() beforehand.
func (o *DeleteDataCleaningProfileParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
