// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	swagmodels "github.com/accedian/adh-gather/swagmodels"
)

// DeleteConnectorInstanceV2OKCode is the HTTP code returned for type DeleteConnectorInstanceV2OK
const DeleteConnectorInstanceV2OKCode int = 200

/*DeleteConnectorInstanceV2OK delete connector instance v2 o k

swagger:response deleteConnectorInstanceV2OK
*/
type DeleteConnectorInstanceV2OK struct {

	/*
	  In: Body
	*/
	Payload *swagmodels.ConnectorInstanceResponse `json:"body,omitempty"`
}

// NewDeleteConnectorInstanceV2OK creates DeleteConnectorInstanceV2OK with default headers values
func NewDeleteConnectorInstanceV2OK() *DeleteConnectorInstanceV2OK {

	return &DeleteConnectorInstanceV2OK{}
}

// WithPayload adds the payload to the delete connector instance v2 o k response
func (o *DeleteConnectorInstanceV2OK) WithPayload(payload *swagmodels.ConnectorInstanceResponse) *DeleteConnectorInstanceV2OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete connector instance v2 o k response
func (o *DeleteConnectorInstanceV2OK) SetPayload(payload *swagmodels.ConnectorInstanceResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConnectorInstanceV2OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConnectorInstanceV2ForbiddenCode is the HTTP code returned for type DeleteConnectorInstanceV2Forbidden
const DeleteConnectorInstanceV2ForbiddenCode int = 403

/*DeleteConnectorInstanceV2Forbidden Requestor does not have authorization to perform this action

swagger:response deleteConnectorInstanceV2Forbidden
*/
type DeleteConnectorInstanceV2Forbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteConnectorInstanceV2Forbidden creates DeleteConnectorInstanceV2Forbidden with default headers values
func NewDeleteConnectorInstanceV2Forbidden() *DeleteConnectorInstanceV2Forbidden {

	return &DeleteConnectorInstanceV2Forbidden{}
}

// WithPayload adds the payload to the delete connector instance v2 forbidden response
func (o *DeleteConnectorInstanceV2Forbidden) WithPayload(payload string) *DeleteConnectorInstanceV2Forbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete connector instance v2 forbidden response
func (o *DeleteConnectorInstanceV2Forbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConnectorInstanceV2Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DeleteConnectorInstanceV2NotFoundCode is the HTTP code returned for type DeleteConnectorInstanceV2NotFound
const DeleteConnectorInstanceV2NotFoundCode int = 404

/*DeleteConnectorInstanceV2NotFound The requested Connector Instance is not provisioned

swagger:response deleteConnectorInstanceV2NotFound
*/
type DeleteConnectorInstanceV2NotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteConnectorInstanceV2NotFound creates DeleteConnectorInstanceV2NotFound with default headers values
func NewDeleteConnectorInstanceV2NotFound() *DeleteConnectorInstanceV2NotFound {

	return &DeleteConnectorInstanceV2NotFound{}
}

// WithPayload adds the payload to the delete connector instance v2 not found response
func (o *DeleteConnectorInstanceV2NotFound) WithPayload(payload string) *DeleteConnectorInstanceV2NotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete connector instance v2 not found response
func (o *DeleteConnectorInstanceV2NotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConnectorInstanceV2NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DeleteConnectorInstanceV2InternalServerErrorCode is the HTTP code returned for type DeleteConnectorInstanceV2InternalServerError
const DeleteConnectorInstanceV2InternalServerErrorCode int = 500

/*DeleteConnectorInstanceV2InternalServerError Unexpected error processing request

swagger:response deleteConnectorInstanceV2InternalServerError
*/
type DeleteConnectorInstanceV2InternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteConnectorInstanceV2InternalServerError creates DeleteConnectorInstanceV2InternalServerError with default headers values
func NewDeleteConnectorInstanceV2InternalServerError() *DeleteConnectorInstanceV2InternalServerError {

	return &DeleteConnectorInstanceV2InternalServerError{}
}

// WithPayload adds the payload to the delete connector instance v2 internal server error response
func (o *DeleteConnectorInstanceV2InternalServerError) WithPayload(payload string) *DeleteConnectorInstanceV2InternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete connector instance v2 internal server error response
func (o *DeleteConnectorInstanceV2InternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConnectorInstanceV2InternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
