// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DownloadRoadrunnerHandlerFunc turns a function with the right signature into a download roadrunner handler
type DownloadRoadrunnerHandlerFunc func(DownloadRoadrunnerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DownloadRoadrunnerHandlerFunc) Handle(params DownloadRoadrunnerParams) middleware.Responder {
	return fn(params)
}

// DownloadRoadrunnerHandler interface for that can handle valid download roadrunner params
type DownloadRoadrunnerHandler interface {
	Handle(DownloadRoadrunnerParams) middleware.Responder
}

// NewDownloadRoadrunner creates a new http.Handler for the download roadrunner operation
func NewDownloadRoadrunner(ctx *middleware.Context, handler DownloadRoadrunnerHandler) *DownloadRoadrunner {
	return &DownloadRoadrunner{Context: ctx, Handler: handler}
}

/*DownloadRoadrunner swagger:route GET /v2/distribution/download-roadrunner TenantProvisioningServiceV2 downloadRoadrunner

Download a roadrunner tarball ready for installing

*/
type DownloadRoadrunner struct {
	Context *middleware.Context
	Handler DownloadRoadrunnerHandler
}

func (o *DownloadRoadrunner) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDownloadRoadrunnerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
