// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCardV2HandlerFunc turns a function with the right signature into a get card v2 handler
type GetCardV2HandlerFunc func(GetCardV2Params) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCardV2HandlerFunc) Handle(params GetCardV2Params) middleware.Responder {
	return fn(params)
}

// GetCardV2Handler interface for that can handle valid get card v2 params
type GetCardV2Handler interface {
	Handle(GetCardV2Params) middleware.Responder
}

// NewGetCardV2 creates a new http.Handler for the get card v2 operation
func NewGetCardV2(ctx *middleware.Context, handler GetCardV2Handler) *GetCardV2 {
	return &GetCardV2{Context: ctx, Handler: handler}
}

/*GetCardV2 swagger:route GET /v2/cards/{cardId} TenantProvisioningServiceV2 getCardV2

Retrieve a Tenant Card by Id.

*/
type GetCardV2 struct {
	Context *middleware.Context
	Handler GetCardV2Handler
}

func (o *GetCardV2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCardV2Params()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
