// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllCardsV2HandlerFunc turns a function with the right signature into a get all cards v2 handler
type GetAllCardsV2HandlerFunc func(GetAllCardsV2Params) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllCardsV2HandlerFunc) Handle(params GetAllCardsV2Params) middleware.Responder {
	return fn(params)
}

// GetAllCardsV2Handler interface for that can handle valid get all cards v2 params
type GetAllCardsV2Handler interface {
	Handle(GetAllCardsV2Params) middleware.Responder
}

// NewGetAllCardsV2 creates a new http.Handler for the get all cards v2 operation
func NewGetAllCardsV2(ctx *middleware.Context, handler GetAllCardsV2Handler) *GetAllCardsV2 {
	return &GetAllCardsV2{Context: ctx, Handler: handler}
}

/*GetAllCardsV2 swagger:route GET /v2/cards TenantProvisioningServiceV2 getAllCardsV2

Retrieve all Cards for the specified Tenant.

*/
type GetAllCardsV2 struct {
	Context *middleware.Context
	Handler GetAllCardsV2Handler
}

func (o *GetAllCardsV2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllCardsV2Params()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
