// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllConnectorConfigsV2HandlerFunc turns a function with the right signature into a get all connector configs v2 handler
type GetAllConnectorConfigsV2HandlerFunc func(GetAllConnectorConfigsV2Params) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllConnectorConfigsV2HandlerFunc) Handle(params GetAllConnectorConfigsV2Params) middleware.Responder {
	return fn(params)
}

// GetAllConnectorConfigsV2Handler interface for that can handle valid get all connector configs v2 params
type GetAllConnectorConfigsV2Handler interface {
	Handle(GetAllConnectorConfigsV2Params) middleware.Responder
}

// NewGetAllConnectorConfigsV2 creates a new http.Handler for the get all connector configs v2 operation
func NewGetAllConnectorConfigsV2(ctx *middleware.Context, handler GetAllConnectorConfigsV2Handler) *GetAllConnectorConfigsV2 {
	return &GetAllConnectorConfigsV2{Context: ctx, Handler: handler}
}

/*GetAllConnectorConfigsV2 swagger:route GET /v2/connector-configs TenantProvisioningServiceV2 getAllConnectorConfigsV2

Retrieve all ConnectorConfigs for the specified Tenant.

*/
type GetAllConnectorConfigsV2 struct {
	Context *middleware.Context
	Handler GetAllConnectorConfigsV2Handler
}

func (o *GetAllConnectorConfigsV2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllConnectorConfigsV2Params()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
