// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllThresholdProfilesV2HandlerFunc turns a function with the right signature into a get all threshold profiles v2 handler
type GetAllThresholdProfilesV2HandlerFunc func(GetAllThresholdProfilesV2Params) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllThresholdProfilesV2HandlerFunc) Handle(params GetAllThresholdProfilesV2Params) middleware.Responder {
	return fn(params)
}

// GetAllThresholdProfilesV2Handler interface for that can handle valid get all threshold profiles v2 params
type GetAllThresholdProfilesV2Handler interface {
	Handle(GetAllThresholdProfilesV2Params) middleware.Responder
}

// NewGetAllThresholdProfilesV2 creates a new http.Handler for the get all threshold profiles v2 operation
func NewGetAllThresholdProfilesV2(ctx *middleware.Context, handler GetAllThresholdProfilesV2Handler) *GetAllThresholdProfilesV2 {
	return &GetAllThresholdProfilesV2{Context: ctx, Handler: handler}
}

/*GetAllThresholdProfilesV2 swagger:route GET /v2/threshold-profiles TenantProvisioningServiceV2 getAllThresholdProfilesV2

Retrieve all Threshold Profiles for the specified Tenant.

*/
type GetAllThresholdProfilesV2 struct {
	Context *middleware.Context
	Handler GetAllThresholdProfilesV2Handler
}

func (o *GetAllThresholdProfilesV2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllThresholdProfilesV2Params()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
