// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateMetricBaselineV2HandlerFunc turns a function with the right signature into a update metric baseline v2 handler
type UpdateMetricBaselineV2HandlerFunc func(UpdateMetricBaselineV2Params) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateMetricBaselineV2HandlerFunc) Handle(params UpdateMetricBaselineV2Params) middleware.Responder {
	return fn(params)
}

// UpdateMetricBaselineV2Handler interface for that can handle valid update metric baseline v2 params
type UpdateMetricBaselineV2Handler interface {
	Handle(UpdateMetricBaselineV2Params) middleware.Responder
}

// NewUpdateMetricBaselineV2 creates a new http.Handler for the update metric baseline v2 operation
func NewUpdateMetricBaselineV2(ctx *middleware.Context, handler UpdateMetricBaselineV2Handler) *UpdateMetricBaselineV2 {
	return &UpdateMetricBaselineV2{Context: ctx, Handler: handler}
}

/*UpdateMetricBaselineV2 swagger:route PATCH /v2/metric-baselines/{metricBaselineId} TenantProvisioningServiceV2 updateMetricBaselineV2

Update a Tenant Metric Baseline

*/
type UpdateMetricBaselineV2 struct {
	Context *middleware.Context
	Handler UpdateMetricBaselineV2Handler
}

func (o *UpdateMetricBaselineV2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateMetricBaselineV2Params()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
