// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	swagmodels "github.com/accedian/adh-gather/swagmodels"
)

// UpdateReportScheduleConfigV2OKCode is the HTTP code returned for type UpdateReportScheduleConfigV2OK
const UpdateReportScheduleConfigV2OKCode int = 200

/*UpdateReportScheduleConfigV2OK update report schedule config v2 o k

swagger:response updateReportScheduleConfigV2OK
*/
type UpdateReportScheduleConfigV2OK struct {

	/*
	  In: Body
	*/
	Payload *swagmodels.ReportScheduleConfigResponse `json:"body,omitempty"`
}

// NewUpdateReportScheduleConfigV2OK creates UpdateReportScheduleConfigV2OK with default headers values
func NewUpdateReportScheduleConfigV2OK() *UpdateReportScheduleConfigV2OK {

	return &UpdateReportScheduleConfigV2OK{}
}

// WithPayload adds the payload to the update report schedule config v2 o k response
func (o *UpdateReportScheduleConfigV2OK) WithPayload(payload *swagmodels.ReportScheduleConfigResponse) *UpdateReportScheduleConfigV2OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update report schedule config v2 o k response
func (o *UpdateReportScheduleConfigV2OK) SetPayload(payload *swagmodels.ReportScheduleConfigResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateReportScheduleConfigV2OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateReportScheduleConfigV2BadRequestCode is the HTTP code returned for type UpdateReportScheduleConfigV2BadRequest
const UpdateReportScheduleConfigV2BadRequestCode int = 400

/*UpdateReportScheduleConfigV2BadRequest Request data does not pass validation

swagger:response updateReportScheduleConfigV2BadRequest
*/
type UpdateReportScheduleConfigV2BadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateReportScheduleConfigV2BadRequest creates UpdateReportScheduleConfigV2BadRequest with default headers values
func NewUpdateReportScheduleConfigV2BadRequest() *UpdateReportScheduleConfigV2BadRequest {

	return &UpdateReportScheduleConfigV2BadRequest{}
}

// WithPayload adds the payload to the update report schedule config v2 bad request response
func (o *UpdateReportScheduleConfigV2BadRequest) WithPayload(payload string) *UpdateReportScheduleConfigV2BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update report schedule config v2 bad request response
func (o *UpdateReportScheduleConfigV2BadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateReportScheduleConfigV2BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UpdateReportScheduleConfigV2ForbiddenCode is the HTTP code returned for type UpdateReportScheduleConfigV2Forbidden
const UpdateReportScheduleConfigV2ForbiddenCode int = 403

/*UpdateReportScheduleConfigV2Forbidden Requestor does not have authorization to perform this action

swagger:response updateReportScheduleConfigV2Forbidden
*/
type UpdateReportScheduleConfigV2Forbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateReportScheduleConfigV2Forbidden creates UpdateReportScheduleConfigV2Forbidden with default headers values
func NewUpdateReportScheduleConfigV2Forbidden() *UpdateReportScheduleConfigV2Forbidden {

	return &UpdateReportScheduleConfigV2Forbidden{}
}

// WithPayload adds the payload to the update report schedule config v2 forbidden response
func (o *UpdateReportScheduleConfigV2Forbidden) WithPayload(payload string) *UpdateReportScheduleConfigV2Forbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update report schedule config v2 forbidden response
func (o *UpdateReportScheduleConfigV2Forbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateReportScheduleConfigV2Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UpdateReportScheduleConfigV2NotFoundCode is the HTTP code returned for type UpdateReportScheduleConfigV2NotFound
const UpdateReportScheduleConfigV2NotFoundCode int = 404

/*UpdateReportScheduleConfigV2NotFound Requested Report Schedule Configuration is not provisioned

swagger:response updateReportScheduleConfigV2NotFound
*/
type UpdateReportScheduleConfigV2NotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateReportScheduleConfigV2NotFound creates UpdateReportScheduleConfigV2NotFound with default headers values
func NewUpdateReportScheduleConfigV2NotFound() *UpdateReportScheduleConfigV2NotFound {

	return &UpdateReportScheduleConfigV2NotFound{}
}

// WithPayload adds the payload to the update report schedule config v2 not found response
func (o *UpdateReportScheduleConfigV2NotFound) WithPayload(payload string) *UpdateReportScheduleConfigV2NotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update report schedule config v2 not found response
func (o *UpdateReportScheduleConfigV2NotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateReportScheduleConfigV2NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UpdateReportScheduleConfigV2ConflictCode is the HTTP code returned for type UpdateReportScheduleConfigV2Conflict
const UpdateReportScheduleConfigV2ConflictCode int = 409

/*UpdateReportScheduleConfigV2Conflict Incorrect revision provided for this update request

swagger:response updateReportScheduleConfigV2Conflict
*/
type UpdateReportScheduleConfigV2Conflict struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateReportScheduleConfigV2Conflict creates UpdateReportScheduleConfigV2Conflict with default headers values
func NewUpdateReportScheduleConfigV2Conflict() *UpdateReportScheduleConfigV2Conflict {

	return &UpdateReportScheduleConfigV2Conflict{}
}

// WithPayload adds the payload to the update report schedule config v2 conflict response
func (o *UpdateReportScheduleConfigV2Conflict) WithPayload(payload string) *UpdateReportScheduleConfigV2Conflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update report schedule config v2 conflict response
func (o *UpdateReportScheduleConfigV2Conflict) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateReportScheduleConfigV2Conflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UpdateReportScheduleConfigV2InternalServerErrorCode is the HTTP code returned for type UpdateReportScheduleConfigV2InternalServerError
const UpdateReportScheduleConfigV2InternalServerErrorCode int = 500

/*UpdateReportScheduleConfigV2InternalServerError Unexpected error processing request

swagger:response updateReportScheduleConfigV2InternalServerError
*/
type UpdateReportScheduleConfigV2InternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateReportScheduleConfigV2InternalServerError creates UpdateReportScheduleConfigV2InternalServerError with default headers values
func NewUpdateReportScheduleConfigV2InternalServerError() *UpdateReportScheduleConfigV2InternalServerError {

	return &UpdateReportScheduleConfigV2InternalServerError{}
}

// WithPayload adds the payload to the update report schedule config v2 internal server error response
func (o *UpdateReportScheduleConfigV2InternalServerError) WithPayload(payload string) *UpdateReportScheduleConfigV2InternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update report schedule config v2 internal server error response
func (o *UpdateReportScheduleConfigV2InternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateReportScheduleConfigV2InternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
