// Code generated by go-swagger; DO NOT EDIT.

package metrics_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	swagmodels "github.com/accedian/adh-gather/swagmodels"
)

// GetThresholdCrossingByMonitoredObjectTopNOKCode is the HTTP code returned for type GetThresholdCrossingByMonitoredObjectTopNOK
const GetThresholdCrossingByMonitoredObjectTopNOKCode int = 200

/*GetThresholdCrossingByMonitoredObjectTopNOK get threshold crossing by monitored object top n o k

swagger:response getThresholdCrossingByMonitoredObjectTopNOK
*/
type GetThresholdCrossingByMonitoredObjectTopNOK struct {

	/*
	  In: Body
	*/
	Payload *swagmodels.GathergrpcJSONAPIObject `json:"body,omitempty"`
}

// NewGetThresholdCrossingByMonitoredObjectTopNOK creates GetThresholdCrossingByMonitoredObjectTopNOK with default headers values
func NewGetThresholdCrossingByMonitoredObjectTopNOK() *GetThresholdCrossingByMonitoredObjectTopNOK {

	return &GetThresholdCrossingByMonitoredObjectTopNOK{}
}

// WithPayload adds the payload to the get threshold crossing by monitored object top n o k response
func (o *GetThresholdCrossingByMonitoredObjectTopNOK) WithPayload(payload *swagmodels.GathergrpcJSONAPIObject) *GetThresholdCrossingByMonitoredObjectTopNOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get threshold crossing by monitored object top n o k response
func (o *GetThresholdCrossingByMonitoredObjectTopNOK) SetPayload(payload *swagmodels.GathergrpcJSONAPIObject) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetThresholdCrossingByMonitoredObjectTopNOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetThresholdCrossingByMonitoredObjectTopNBadRequestCode is the HTTP code returned for type GetThresholdCrossingByMonitoredObjectTopNBadRequest
const GetThresholdCrossingByMonitoredObjectTopNBadRequestCode int = 400

/*GetThresholdCrossingByMonitoredObjectTopNBadRequest Request data does not pass validation

swagger:response getThresholdCrossingByMonitoredObjectTopNBadRequest
*/
type GetThresholdCrossingByMonitoredObjectTopNBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetThresholdCrossingByMonitoredObjectTopNBadRequest creates GetThresholdCrossingByMonitoredObjectTopNBadRequest with default headers values
func NewGetThresholdCrossingByMonitoredObjectTopNBadRequest() *GetThresholdCrossingByMonitoredObjectTopNBadRequest {

	return &GetThresholdCrossingByMonitoredObjectTopNBadRequest{}
}

// WithPayload adds the payload to the get threshold crossing by monitored object top n bad request response
func (o *GetThresholdCrossingByMonitoredObjectTopNBadRequest) WithPayload(payload string) *GetThresholdCrossingByMonitoredObjectTopNBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get threshold crossing by monitored object top n bad request response
func (o *GetThresholdCrossingByMonitoredObjectTopNBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetThresholdCrossingByMonitoredObjectTopNBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetThresholdCrossingByMonitoredObjectTopNForbiddenCode is the HTTP code returned for type GetThresholdCrossingByMonitoredObjectTopNForbidden
const GetThresholdCrossingByMonitoredObjectTopNForbiddenCode int = 403

/*GetThresholdCrossingByMonitoredObjectTopNForbidden Requestor does not have authorization to perform this action

swagger:response getThresholdCrossingByMonitoredObjectTopNForbidden
*/
type GetThresholdCrossingByMonitoredObjectTopNForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetThresholdCrossingByMonitoredObjectTopNForbidden creates GetThresholdCrossingByMonitoredObjectTopNForbidden with default headers values
func NewGetThresholdCrossingByMonitoredObjectTopNForbidden() *GetThresholdCrossingByMonitoredObjectTopNForbidden {

	return &GetThresholdCrossingByMonitoredObjectTopNForbidden{}
}

// WithPayload adds the payload to the get threshold crossing by monitored object top n forbidden response
func (o *GetThresholdCrossingByMonitoredObjectTopNForbidden) WithPayload(payload string) *GetThresholdCrossingByMonitoredObjectTopNForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get threshold crossing by monitored object top n forbidden response
func (o *GetThresholdCrossingByMonitoredObjectTopNForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetThresholdCrossingByMonitoredObjectTopNForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetThresholdCrossingByMonitoredObjectTopNNotFoundCode is the HTTP code returned for type GetThresholdCrossingByMonitoredObjectTopNNotFound
const GetThresholdCrossingByMonitoredObjectTopNNotFoundCode int = 404

/*GetThresholdCrossingByMonitoredObjectTopNNotFound Threshold profile not found

swagger:response getThresholdCrossingByMonitoredObjectTopNNotFound
*/
type GetThresholdCrossingByMonitoredObjectTopNNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetThresholdCrossingByMonitoredObjectTopNNotFound creates GetThresholdCrossingByMonitoredObjectTopNNotFound with default headers values
func NewGetThresholdCrossingByMonitoredObjectTopNNotFound() *GetThresholdCrossingByMonitoredObjectTopNNotFound {

	return &GetThresholdCrossingByMonitoredObjectTopNNotFound{}
}

// WithPayload adds the payload to the get threshold crossing by monitored object top n not found response
func (o *GetThresholdCrossingByMonitoredObjectTopNNotFound) WithPayload(payload string) *GetThresholdCrossingByMonitoredObjectTopNNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get threshold crossing by monitored object top n not found response
func (o *GetThresholdCrossingByMonitoredObjectTopNNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetThresholdCrossingByMonitoredObjectTopNNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetThresholdCrossingByMonitoredObjectTopNInternalServerErrorCode is the HTTP code returned for type GetThresholdCrossingByMonitoredObjectTopNInternalServerError
const GetThresholdCrossingByMonitoredObjectTopNInternalServerErrorCode int = 500

/*GetThresholdCrossingByMonitoredObjectTopNInternalServerError Unexpected error processing request

swagger:response getThresholdCrossingByMonitoredObjectTopNInternalServerError
*/
type GetThresholdCrossingByMonitoredObjectTopNInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetThresholdCrossingByMonitoredObjectTopNInternalServerError creates GetThresholdCrossingByMonitoredObjectTopNInternalServerError with default headers values
func NewGetThresholdCrossingByMonitoredObjectTopNInternalServerError() *GetThresholdCrossingByMonitoredObjectTopNInternalServerError {

	return &GetThresholdCrossingByMonitoredObjectTopNInternalServerError{}
}

// WithPayload adds the payload to the get threshold crossing by monitored object top n internal server error response
func (o *GetThresholdCrossingByMonitoredObjectTopNInternalServerError) WithPayload(payload string) *GetThresholdCrossingByMonitoredObjectTopNInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get threshold crossing by monitored object top n internal server error response
func (o *GetThresholdCrossingByMonitoredObjectTopNInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetThresholdCrossingByMonitoredObjectTopNInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
