serverConfig:
  Datastore:
    bindIP: http://localhost
    bindPort: 8888
  REST:
    bindIP: http://localhost
    bindPort: 10001
  GRPC:
    bindIP: http://localhost
    bindPort: 10000
  StartupArgs:
    adminDB: 1
    tenantDB: 1