server:
  datastore:
    ip: http://localhost
    port: 5984
  rest:
    ip: 0.0.0.0
    port: 10001
  grpc:
    ip: 0.0.0.0
    port: 10002
  cors:
    allowedorigins: 
      - http://localhost:4200
args:
  admindb: 
    name: adh-admin
    impl: 1
  tenantdb: 
    impl: 1
  pouchplugindb:
    impl: 1
  debug: true

druid:
  server: "https://broker.skoa.npav.accedian.net"
  table: "npav-ts-metrics"
  auth: "https://www.googleapis.com/oauth2/v4/token?client_id=627634877761-jsgt56b08875ahddn72dmipfrp848ou4.apps.googleusercontent.com&client_secret=ArWEZCMyZ0SrsJzSiqGU10aE&refresh_token=1%2FCmG4jLIxA7pmNBUrxBPW1QFlTAM2mhHfqV_Bw2S-sbs&grant_type=refresh_token&audience=627634877761-gsci6s8gheq6rktbf17h2bfg47o9paol.apps.googleusercontent.com"
    
    
