server:
  datastore:
    ip: http://localhost
    port: 5984
    batchsize: 1000
  rest:
    ip: 0.0.0.0
    port: 10001
  grpc:
    ip: 0.0.0.0
    port: 10002
  monitoring:
    port: 9191
  cors:
    allowedorigins: 
      - http://localhost:4200
      - http://localhost:9000
args:
  admindb: 
    name: adh-admin
    impl: 1
  tenantdb: 
    impl: 1
  pouchplugindb:
    impl: 1
  testdatadb:
    impl: 1
  debug: true
  maxConcurrentPouchAPICalls:  1000
  maxConcurrentProvAPICalls:   1000
  maxConcurrentMetricAPICalls: 500

kafka:
  broker: kafka:9092

druid:
    #auth: "https://accedian-dh2.npav.accedian.net/api/v1/auth/login/"
  auth: "https://abatos.npav.accedian.net/api/v1/auth/login/"
  username: "admin@datahub.com"
  password: "AccedianPass"
  cookieName: "skylight-aaa"
  broker:
      #server: "https://accedian-dh2.npav.accedian.net/broker"
    server: "https://megatron.npav.accedian.net/broker"
    table: "npav-ts-metrics"


  coordinator:
    server: "https://megatron.npav.accedian.net/coordinator"
    port: -1
