server:
  datastore:
    ip: http://localhost
    port: 6684 
    batchsize: 1000
  rest:
    ip: 0.0.0.0
    port: 10001
  grpc:
    ip: 0.0.0.0
    port: 10002
  monitoring:
    port: 9191
  cors:
    allowedorigins: 
      - http://localhost:4200
args:
  admindb: 
    name: adh-admin
    impl: 1
  tenantdb: 
    impl: 1
  pouchplugindb:
    impl: 1
  testdatadb:
    impl: 1
  debug: true
  maxConcurrentPouchAPICalls:  1000
  maxConcurrentProvAPICalls:   1000
  maxConcurrentMetricAPICalls: 500
  coltmef:
    enabled: false
    server: "https://demo.ondemand.colt.net/api/performance/recommendation"
    appID: "datahubtest"
    secret: "test123"
    statusRetryCount: 10
    checkpoint1: 300
    checkpoint2: 600
    checkpoint3: 900
  metricbaselines:
    numworkers: 10
    maxnumjobs: 100
    impl: 2
    ip: 127.0.0.1
    port: 5432
    user: postgres
    password: mysecretpassword
    dbname: testdb
    schemadir: "datastore/postgres/test"

kafka:
  broker: "localhost:9092"

druid:
  broker:
    server: "http://localhost:8082"
    table: "npav-ts-metrics"
