server:
  datastore:
    ip: http://localhost
    port: 5984
  rest:
    ip: 0.0.0.0
    port: 10001
  grpc:
    ip: 0.0.0.0
    port: 10002
  cors:
    allowedorigins: 
      - http://localhost:4200
args:
  admindb: 
    name: adh-admin
    impl: 1
  tenantdb: 
    impl: 1
  pouchplugindb:
    impl: 1
  debug: true

druid:
  server: "https://broker.proto.npav.accedian.net"
  table: "NPAVKPI2"
