serverConfig:
  Datastore:
    bindIP: http://localhost
    bindPort: 5984
  REST:
    bindIP: http://localhost
    bindPort: 10001
  GRPC:
    bindIP: http://localhost
    bindPort: 10002
  StartupArgs:
    adminDB: 
      name: adh-admin
      impl: 1
    tenantDB: 1
    pouchPluginDB: 1
    debug: false