server:
  datastore:
    ip: http://localhost
    port: 5984
  rest:
    ip: 0.0.0.0
    port: 10001
  grpc:
    ip: 0.0.0.0
    port: 10002
  monitoring:
    port: 9191
  cors:
    allowedorigins: 
      - http://localhost:4200
args:
  admindb: 
    name: adh-admin
    impl: 1
  tenantdb: 
    impl: 1
  pouchplugindb:
    impl: 1
  testdatadb:
    impl: 1
  debug: true
  maxConcurrentPouchAPICalls:  1000
  maxConcurrentProvAPICalls:   1000
  maxConcurrentMetricAPICalls: 500

druid:
  server: "https://broker.mpreston.npav.accedian.net"
  table: "npav-ts-metrics"
  auth: "https://www.googleapis.com/oauth2/v4/token?client_id=627634877761-jsgt56b08875ahddn72dmipfrp848ou4.apps.googleusercontent.com&client_secret=ArWEZCMyZ0SrsJzSiqGU10aE&refresh_token=1/73yKOIRcqC7WEFIDA-p1nnnhoXvQvBMKAryS967P7SU&grant_type=refresh_token&audience=627634877761-m2ag3kvptgns0mk53s1pqvkfq2va8b1n.apps.googleusercontent.com"

    #"https://www.googleapis.com/oauth2/v4/token?client_id=627634877761-jsgt56b08875ahddn72dmipfrp848ou4.apps.googleusercontent.com&client_secret=ArWEZCMyZ0SrsJzSiqGU10aE&refresh_token=1%2FDfvhAZKYRY2MM90DbK66VfIvbsx7Phh1fLnVSxqRbYc&grant_type=refresh_token&audience=627634877761-fuiuhml29ce7985ua5rcjm2s3adk797v.apps.googleusercontent.com"
