// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gathergrpc/adminModels.proto

package gathergrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Provides the metadata of a Tenant. This information is used to
// idetify/describe a full Tenant entity.
type TenantDescriptorData struct {
	Datatype              string    `protobuf:"bytes,2,opt,name=datatype" json:"datatype,omitempty"`
	Name                  string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	UrlSubdomain          string    `protobuf:"bytes,4,opt,name=urlSubdomain" json:"urlSubdomain,omitempty"`
	State                 UserState `protobuf:"varint,5,opt,name=state,enum=gathergrpc.UserState" json:"state,omitempty"`
	CreatedTimestamp      int64     `protobuf:"varint,6,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp int64     `protobuf:"varint,7,opt,name=lastModifiedTimestamp" json:"lastModifiedTimestamp,omitempty"`
}

func (m *TenantDescriptorData) Reset()                    { *m = TenantDescriptorData{} }
func (m *TenantDescriptorData) String() string            { return proto.CompactTextString(m) }
func (*TenantDescriptorData) ProtoMessage()               {}
func (*TenantDescriptorData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *TenantDescriptorData) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

func (m *TenantDescriptorData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TenantDescriptorData) GetUrlSubdomain() string {
	if m != nil {
		return m.UrlSubdomain
	}
	return ""
}

func (m *TenantDescriptorData) GetState() UserState {
	if m != nil {
		return m.State
	}
	return UserState_USER_UNKNOWN
}

func (m *TenantDescriptorData) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *TenantDescriptorData) GetLastModifiedTimestamp() int64 {
	if m != nil {
		return m.LastModifiedTimestamp
	}
	return 0
}

// TenantDescriptor - wrapper for passing TenantDescriptor
// data as a request to the service.
type TenantDescriptor struct {
	XId  string                `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string                `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *TenantDescriptorData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *TenantDescriptor) Reset()                    { *m = TenantDescriptor{} }
func (m *TenantDescriptor) String() string            { return proto.CompactTextString(m) }
func (*TenantDescriptor) ProtoMessage()               {}
func (*TenantDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *TenantDescriptor) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *TenantDescriptor) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *TenantDescriptor) GetData() *TenantDescriptorData {
	if m != nil {
		return m.Data
	}
	return nil
}

// Wrapper message to provide a response in the form of
// a container of multiple TenantDescriptor objects.
type TenantDescriptorList struct {
	Data []*TenantDescriptor `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *TenantDescriptorList) Reset()                    { *m = TenantDescriptorList{} }
func (m *TenantDescriptorList) String() string            { return proto.CompactTextString(m) }
func (*TenantDescriptorList) ProtoMessage()               {}
func (*TenantDescriptorList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *TenantDescriptorList) GetData() []*TenantDescriptor {
	if m != nil {
		return m.Data
	}
	return nil
}

// User data for an Adminstrative User.
type AdminUserData struct {
	Datatype              string    `protobuf:"bytes,2,opt,name=datatype" json:"datatype,omitempty"`
	Username              string    `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Password              string    `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	SendOnboardingEmail   bool      `protobuf:"varint,5,opt,name=sendOnboardingEmail" json:"sendOnboardingEmail,omitempty"`
	OnboardingToken       string    `protobuf:"bytes,6,opt,name=onboardingToken" json:"onboardingToken,omitempty"`
	UserVerified          bool      `protobuf:"varint,7,opt,name=userVerified" json:"userVerified,omitempty"`
	State                 UserState `protobuf:"varint,8,opt,name=state,enum=gathergrpc.UserState" json:"state,omitempty"`
	CreatedTimestamp      int64     `protobuf:"varint,9,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp int64     `protobuf:"varint,10,opt,name=lastModifiedTimestamp" json:"lastModifiedTimestamp,omitempty"`
}

func (m *AdminUserData) Reset()                    { *m = AdminUserData{} }
func (m *AdminUserData) String() string            { return proto.CompactTextString(m) }
func (*AdminUserData) ProtoMessage()               {}
func (*AdminUserData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *AdminUserData) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

func (m *AdminUserData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AdminUserData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AdminUserData) GetSendOnboardingEmail() bool {
	if m != nil {
		return m.SendOnboardingEmail
	}
	return false
}

func (m *AdminUserData) GetOnboardingToken() string {
	if m != nil {
		return m.OnboardingToken
	}
	return ""
}

func (m *AdminUserData) GetUserVerified() bool {
	if m != nil {
		return m.UserVerified
	}
	return false
}

func (m *AdminUserData) GetState() UserState {
	if m != nil {
		return m.State
	}
	return UserState_USER_UNKNOWN
}

func (m *AdminUserData) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *AdminUserData) GetLastModifiedTimestamp() int64 {
	if m != nil {
		return m.LastModifiedTimestamp
	}
	return 0
}

// AdminUser - wrapper for passing AdminUser
// data as a request to the service.
type AdminUser struct {
	XId  string         `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string         `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *AdminUserData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *AdminUser) Reset()                    { *m = AdminUser{} }
func (m *AdminUser) String() string            { return proto.CompactTextString(m) }
func (*AdminUser) ProtoMessage()               {}
func (*AdminUser) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *AdminUser) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *AdminUser) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *AdminUser) GetData() *AdminUserData {
	if m != nil {
		return m.Data
	}
	return nil
}

// Wrapper message to provide a response in the form of
// a container of multiple AdminUser objects.
type AdminUserList struct {
	Data []*AdminUser `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *AdminUserList) Reset()                    { *m = AdminUserList{} }
func (m *AdminUserList) String() string            { return proto.CompactTextString(m) }
func (*AdminUserList) ProtoMessage()               {}
func (*AdminUserList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *AdminUserList) GetData() []*AdminUser {
	if m != nil {
		return m.Data
	}
	return nil
}

// Stores the available values of the metrics that may be ingested by ADH.
type IngestionDictionaryData struct {
	Datatype              string                                        `protobuf:"bytes,2,opt,name=datatype" json:"datatype,omitempty"`
	Metrics               map[string]*IngestionDictionaryData_MetricMap `protobuf:"bytes,3,rep,name=metrics" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedTimestamp      int64                                         `protobuf:"varint,4,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp int64                                         `protobuf:"varint,5,opt,name=lastModifiedTimestamp" json:"lastModifiedTimestamp,omitempty"`
}

func (m *IngestionDictionaryData) Reset()                    { *m = IngestionDictionaryData{} }
func (m *IngestionDictionaryData) String() string            { return proto.CompactTextString(m) }
func (*IngestionDictionaryData) ProtoMessage()               {}
func (*IngestionDictionaryData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *IngestionDictionaryData) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

func (m *IngestionDictionaryData) GetMetrics() map[string]*IngestionDictionaryData_MetricMap {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *IngestionDictionaryData) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *IngestionDictionaryData) GetLastModifiedTimestamp() int64 {
	if m != nil {
		return m.LastModifiedTimestamp
	}
	return 0
}

type IngestionDictionaryData_UIData struct {
	Group    string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	Position string `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
}

func (m *IngestionDictionaryData_UIData) Reset()         { *m = IngestionDictionaryData_UIData{} }
func (m *IngestionDictionaryData_UIData) String() string { return proto.CompactTextString(m) }
func (*IngestionDictionaryData_UIData) ProtoMessage()    {}
func (*IngestionDictionaryData_UIData) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{6, 0}
}

func (m *IngestionDictionaryData_UIData) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *IngestionDictionaryData_UIData) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type IngestionDictionaryData_MonitoredObjectType struct {
	Key         string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	RawMetricId string   `protobuf:"bytes,2,opt,name=rawMetricId" json:"rawMetricId,omitempty"`
	Units       []string `protobuf:"bytes,3,rep,name=units" json:"units,omitempty"`
	Directions  []string `protobuf:"bytes,4,rep,name=directions" json:"directions,omitempty"`
}

func (m *IngestionDictionaryData_MonitoredObjectType) Reset() {
	*m = IngestionDictionaryData_MonitoredObjectType{}
}
func (m *IngestionDictionaryData_MonitoredObjectType) String() string {
	return proto.CompactTextString(m)
}
func (*IngestionDictionaryData_MonitoredObjectType) ProtoMessage() {}
func (*IngestionDictionaryData_MonitoredObjectType) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{6, 1}
}

func (m *IngestionDictionaryData_MonitoredObjectType) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *IngestionDictionaryData_MonitoredObjectType) GetRawMetricId() string {
	if m != nil {
		return m.RawMetricId
	}
	return ""
}

func (m *IngestionDictionaryData_MonitoredObjectType) GetUnits() []string {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *IngestionDictionaryData_MonitoredObjectType) GetDirections() []string {
	if m != nil {
		return m.Directions
	}
	return nil
}

type IngestionDictionaryData_MetricDefinition struct {
	MonitoredObjectTypes []*IngestionDictionaryData_MonitoredObjectType `protobuf:"bytes,1,rep,name=monitoredObjectTypes" json:"monitoredObjectTypes,omitempty"`
	Ui                   *IngestionDictionaryData_UIData                `protobuf:"bytes,2,opt,name=ui" json:"ui,omitempty"`
}

func (m *IngestionDictionaryData_MetricDefinition) Reset() {
	*m = IngestionDictionaryData_MetricDefinition{}
}
func (m *IngestionDictionaryData_MetricDefinition) String() string { return proto.CompactTextString(m) }
func (*IngestionDictionaryData_MetricDefinition) ProtoMessage()    {}
func (*IngestionDictionaryData_MetricDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{6, 2}
}

func (m *IngestionDictionaryData_MetricDefinition) GetMonitoredObjectTypes() []*IngestionDictionaryData_MonitoredObjectType {
	if m != nil {
		return m.MonitoredObjectTypes
	}
	return nil
}

func (m *IngestionDictionaryData_MetricDefinition) GetUi() *IngestionDictionaryData_UIData {
	if m != nil {
		return m.Ui
	}
	return nil
}

type IngestionDictionaryData_MetricMap struct {
	MetricMap map[string]*IngestionDictionaryData_MetricDefinition `protobuf:"bytes,1,rep,name=metricMap" json:"metricMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *IngestionDictionaryData_MetricMap) Reset()         { *m = IngestionDictionaryData_MetricMap{} }
func (m *IngestionDictionaryData_MetricMap) String() string { return proto.CompactTextString(m) }
func (*IngestionDictionaryData_MetricMap) ProtoMessage()    {}
func (*IngestionDictionaryData_MetricMap) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{6, 3}
}

func (m *IngestionDictionaryData_MetricMap) GetMetricMap() map[string]*IngestionDictionaryData_MetricDefinition {
	if m != nil {
		return m.MetricMap
	}
	return nil
}

// Wrapper fos the object that stores the available values of the metrics that may be ingested by ADH.
type IngestionDictionary struct {
	XId  string                   `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string                   `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *IngestionDictionaryData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *IngestionDictionary) Reset()                    { *m = IngestionDictionary{} }
func (m *IngestionDictionary) String() string            { return proto.CompactTextString(m) }
func (*IngestionDictionary) ProtoMessage()               {}
func (*IngestionDictionary) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *IngestionDictionary) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *IngestionDictionary) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *IngestionDictionary) GetData() *IngestionDictionaryData {
	if m != nil {
		return m.Data
	}
	return nil
}

// ValidTypesRequest - used as query parameters to the API which retrieves various value definitions used
// in Skylight Datahub
type ValidTypesRequest struct {
	MonitoredObjectTypes       bool `protobuf:"varint,1,opt,name=monitoredObjectTypes" json:"monitoredObjectTypes,omitempty"`
	MonitoredObjectDeviceTypes bool `protobuf:"varint,2,opt,name=monitoredObjectDeviceTypes" json:"monitoredObjectDeviceTypes,omitempty"`
}

func (m *ValidTypesRequest) Reset()                    { *m = ValidTypesRequest{} }
func (m *ValidTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*ValidTypesRequest) ProtoMessage()               {}
func (*ValidTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ValidTypesRequest) GetMonitoredObjectTypes() bool {
	if m != nil {
		return m.MonitoredObjectTypes
	}
	return false
}

func (m *ValidTypesRequest) GetMonitoredObjectDeviceTypes() bool {
	if m != nil {
		return m.MonitoredObjectDeviceTypes
	}
	return false
}

type ValidTypesData struct {
	MonitoredObjectTypes       map[string]string `protobuf:"bytes,1,rep,name=monitoredObjectTypes" json:"monitoredObjectTypes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MonitoredObjectDeviceTypes map[string]string `protobuf:"bytes,2,rep,name=monitoredObjectDeviceTypes" json:"monitoredObjectDeviceTypes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedTimestamp           int64             `protobuf:"varint,3,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp      int64             `protobuf:"varint,4,opt,name=lastModifiedTimestamp" json:"lastModifiedTimestamp,omitempty"`
}

func (m *ValidTypesData) Reset()                    { *m = ValidTypesData{} }
func (m *ValidTypesData) String() string            { return proto.CompactTextString(m) }
func (*ValidTypesData) ProtoMessage()               {}
func (*ValidTypesData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *ValidTypesData) GetMonitoredObjectTypes() map[string]string {
	if m != nil {
		return m.MonitoredObjectTypes
	}
	return nil
}

func (m *ValidTypesData) GetMonitoredObjectDeviceTypes() map[string]string {
	if m != nil {
		return m.MonitoredObjectDeviceTypes
	}
	return nil
}

func (m *ValidTypesData) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *ValidTypesData) GetLastModifiedTimestamp() int64 {
	if m != nil {
		return m.LastModifiedTimestamp
	}
	return 0
}

// ValidTypes - contains variious type definitions used in Skylight Datahhub
type ValidTypes struct {
	XId  string          `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string          `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *ValidTypesData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ValidTypes) Reset()                    { *m = ValidTypes{} }
func (m *ValidTypes) String() string            { return proto.CompactTextString(m) }
func (*ValidTypes) ProtoMessage()               {}
func (*ValidTypes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ValidTypes) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *ValidTypes) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *ValidTypes) GetData() *ValidTypesData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TenantDescriptorData)(nil), "gathergrpc.TenantDescriptorData")
	proto.RegisterType((*TenantDescriptor)(nil), "gathergrpc.TenantDescriptor")
	proto.RegisterType((*TenantDescriptorList)(nil), "gathergrpc.TenantDescriptorList")
	proto.RegisterType((*AdminUserData)(nil), "gathergrpc.AdminUserData")
	proto.RegisterType((*AdminUser)(nil), "gathergrpc.AdminUser")
	proto.RegisterType((*AdminUserList)(nil), "gathergrpc.AdminUserList")
	proto.RegisterType((*IngestionDictionaryData)(nil), "gathergrpc.IngestionDictionaryData")
	proto.RegisterType((*IngestionDictionaryData_UIData)(nil), "gathergrpc.IngestionDictionaryData.UIData")
	proto.RegisterType((*IngestionDictionaryData_MonitoredObjectType)(nil), "gathergrpc.IngestionDictionaryData.MonitoredObjectType")
	proto.RegisterType((*IngestionDictionaryData_MetricDefinition)(nil), "gathergrpc.IngestionDictionaryData.MetricDefinition")
	proto.RegisterType((*IngestionDictionaryData_MetricMap)(nil), "gathergrpc.IngestionDictionaryData.MetricMap")
	proto.RegisterType((*IngestionDictionary)(nil), "gathergrpc.IngestionDictionary")
	proto.RegisterType((*ValidTypesRequest)(nil), "gathergrpc.ValidTypesRequest")
	proto.RegisterType((*ValidTypesData)(nil), "gathergrpc.ValidTypesData")
	proto.RegisterType((*ValidTypes)(nil), "gathergrpc.ValidTypes")
}

func init() { proto.RegisterFile("gathergrpc/adminModels.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 860 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x97, 0xe3, 0xa4, 0x8d, 0x5f, 0x96, 0x6e, 0x76, 0x9a, 0x0a, 0xaf, 0xb5, 0x40, 0x14, 0x2e,
	0x61, 0xd1, 0x86, 0x2a, 0x54, 0x5a, 0x14, 0x21, 0x24, 0x44, 0x56, 0x90, 0x15, 0xd1, 0x4a, 0x6e,
	0xda, 0x03, 0x07, 0xca, 0xc4, 0x9e, 0xa6, 0x43, 0x63, 0x8f, 0x99, 0x19, 0xa7, 0x0a, 0x17, 0x8e,
	0x7c, 0x14, 0x3e, 0x04, 0x1f, 0x85, 0x2f, 0x81, 0xb8, 0x71, 0x43, 0x1e, 0x3b, 0xb1, 0xdd, 0x38,
	0x89, 0xc3, 0x29, 0x9e, 0xf7, 0xe6, 0xfd, 0xde, 0x9f, 0xdf, 0x6f, 0x9e, 0x02, 0x2f, 0x66, 0x58,
	0xde, 0x11, 0x3e, 0xe3, 0x81, 0xf3, 0x19, 0x76, 0x3d, 0xea, 0x8f, 0x99, 0x4b, 0xe6, 0xa2, 0x17,
	0x70, 0x26, 0x19, 0x82, 0xd4, 0x6b, 0x7d, 0x90, 0xb9, 0xe9, 0x30, 0xcf, 0x63, 0xb9, 0xab, 0x9d,
	0x7f, 0x35, 0x68, 0x4d, 0x88, 0x8f, 0x7d, 0x39, 0x24, 0xc2, 0xe1, 0x34, 0x90, 0x8c, 0x0f, 0xb1,
	0xc4, 0xc8, 0x82, 0xba, 0x8b, 0x25, 0x96, 0xcb, 0x80, 0x98, 0x95, 0xb6, 0xd6, 0x35, 0xec, 0xf5,
	0x19, 0x21, 0xa8, 0xfa, 0xd8, 0x23, 0xa6, 0xae, 0xec, 0xea, 0x1b, 0x75, 0xe0, 0x49, 0xc8, 0xe7,
	0x97, 0xe1, 0xd4, 0x65, 0x1e, 0xa6, 0xbe, 0x59, 0x55, 0xbe, 0x9c, 0x0d, 0x7d, 0x0a, 0x35, 0x21,
	0xb1, 0x24, 0x66, 0xad, 0xad, 0x75, 0x4f, 0xfa, 0x67, 0xbd, 0xb4, 0xb6, 0xde, 0x95, 0x20, 0xfc,
	0x32, 0x72, 0xda, 0xf1, 0x1d, 0xf4, 0x12, 0x9a, 0x0e, 0x27, 0x58, 0x12, 0x77, 0x42, 0x3d, 0x22,
	0x24, 0xf6, 0x02, 0xf3, 0xa8, 0xad, 0x75, 0x75, 0x7b, 0xc3, 0x8e, 0x2e, 0xe0, 0x6c, 0x8e, 0x85,
	0x1c, 0x33, 0x97, 0xde, 0xd2, 0x6c, 0xc0, 0xb1, 0x0a, 0x28, 0x76, 0x76, 0xe6, 0xd0, 0x7c, 0xdc,
	0x3a, 0x7a, 0x0a, 0xfa, 0x0d, 0x75, 0x4d, 0x4d, 0x55, 0x5f, 0x19, 0xb9, 0xe8, 0x19, 0x54, 0x6f,
	0x38, 0x59, 0x24, 0x33, 0xd0, 0x6d, 0xb2, 0x40, 0x17, 0x50, 0x8d, 0x46, 0xa1, 0xda, 0x6f, 0xf4,
	0xdb, 0xd9, 0x2e, 0x8a, 0x46, 0x69, 0xab, 0xdb, 0x9d, 0xef, 0x36, 0x07, 0xfd, 0x3d, 0x15, 0x12,
	0x9d, 0x27, 0x68, 0x5a, 0x5b, 0xef, 0x36, 0xfa, 0x2f, 0x76, 0xa1, 0x25, 0x48, 0xff, 0x54, 0xe0,
	0xbd, 0xaf, 0x23, 0xd2, 0xa3, 0x99, 0xed, 0x25, 0xcb, 0x82, 0x7a, 0x28, 0x08, 0xcf, 0x10, 0xb6,
	0x3e, 0x47, 0xbe, 0x00, 0x0b, 0xf1, 0xc0, 0xb8, 0x9b, 0x10, 0xb6, 0x3e, 0xa3, 0x73, 0x38, 0x15,
	0xc4, 0x77, 0xdf, 0xf9, 0x53, 0x86, 0xb9, 0x4b, 0xfd, 0xd9, 0x1b, 0x0f, 0xd3, 0xb9, 0xa2, 0xae,
	0x6e, 0x17, 0xb9, 0x50, 0x17, 0x9e, 0xb2, 0xb5, 0x69, 0xc2, 0xee, 0x89, 0xaf, 0x08, 0x33, 0xec,
	0xc7, 0x66, 0x25, 0x16, 0x41, 0xf8, 0x35, 0xe1, 0x8a, 0x12, 0x45, 0x53, 0xdd, 0xce, 0xd9, 0x52,
	0xb1, 0xd4, 0xff, 0xa7, 0x58, 0x8c, 0x43, 0xc5, 0x02, 0xbb, 0xc4, 0xf2, 0x23, 0x18, 0xeb, 0x99,
	0x97, 0x52, 0xc9, 0xab, 0x9c, 0x4a, 0x9e, 0x67, 0xcb, 0xcf, 0x91, 0x97, 0x90, 0x3a, 0xc8, 0x70,
	0xaa, 0x74, 0xf1, 0x49, 0x4e, 0x17, 0x67, 0x85, 0xf1, 0x49, 0xec, 0x1f, 0xc7, 0xf0, 0xfe, 0xc8,
	0x9f, 0x11, 0x21, 0x29, 0xf3, 0x87, 0xd4, 0x89, 0x7e, 0x30, 0x5f, 0xee, 0x95, 0xc6, 0x5b, 0x38,
	0xf6, 0x88, 0xe4, 0xd4, 0x11, 0xa6, 0xae, 0xb2, 0x9c, 0x67, 0xb3, 0x6c, 0x41, 0xec, 0x8d, 0xe3,
	0x90, 0x37, 0xbe, 0xe4, 0x4b, 0x7b, 0x05, 0x50, 0xc8, 0x40, 0xf5, 0x50, 0x06, 0x6a, 0x3b, 0x18,
	0xb0, 0x06, 0x70, 0x74, 0x35, 0x52, 0x3d, 0xb5, 0xa0, 0x36, 0xe3, 0x2c, 0x0c, 0x12, 0x02, 0xe2,
	0x83, 0x12, 0x33, 0x13, 0x34, 0x2a, 0x75, 0xd5, 0xe9, 0xea, 0x6c, 0xfd, 0x06, 0xa7, 0x63, 0xe6,
	0x53, 0xc9, 0x38, 0x71, 0xdf, 0x4d, 0x7f, 0x26, 0x8e, 0x9c, 0x44, 0x03, 0x68, 0x82, 0x7e, 0x4f,
	0x96, 0x09, 0x4c, 0xf4, 0x89, 0xda, 0xd0, 0xe0, 0xf8, 0x21, 0x6e, 0x71, 0xe4, 0x26, 0x38, 0x59,
	0x53, 0x94, 0x3c, 0xf4, 0xa9, 0x8c, 0x47, 0x66, 0xd8, 0xf1, 0x01, 0x7d, 0x08, 0xe0, 0x52, 0x4e,
	0xd4, 0xa0, 0x84, 0x59, 0x55, 0xae, 0x8c, 0xc5, 0xfa, 0x53, 0x83, 0x66, 0x0c, 0x31, 0x24, 0xb7,
	0xd4, 0x57, 0x55, 0xa1, 0x7b, 0x68, 0x79, 0x9b, 0x55, 0x89, 0x84, 0xf2, 0xd7, 0xa5, 0xc8, 0xd8,
	0x8c, 0xb7, 0x0b, 0x41, 0xd1, 0x00, 0x2a, 0x21, 0x55, 0x0d, 0x35, 0xfa, 0x2f, 0xcb, 0x40, 0xc7,
	0xc3, 0xb6, 0x2b, 0x21, 0xb5, 0xfe, 0xd2, 0xc0, 0x88, 0xab, 0x1f, 0xe3, 0x00, 0xfd, 0x00, 0x86,
	0xb7, 0x3a, 0x24, 0xb5, 0x7e, 0x59, 0x5e, 0x38, 0x63, 0x1c, 0xa4, 0x5f, 0xb1, 0x88, 0x52, 0x38,
	0x8b, 0xc3, 0x49, 0xde, 0x59, 0xc0, 0xd1, 0x5b, 0xa8, 0x2d, 0xf0, 0x3c, 0x24, 0x49, 0x33, 0x17,
	0xe5, 0x73, 0xa7, 0xb3, 0xb7, 0x63, 0x88, 0x41, 0xe5, 0x0b, 0xcd, 0xa2, 0xf0, 0x24, 0xab, 0xe9,
	0x82, 0x8c, 0xdf, 0xe4, 0x33, 0xbe, 0x3a, 0xa8, 0xdb, 0x4c, 0xaa, 0x0e, 0x87, 0xd3, 0x82, 0xfb,
	0xa5, 0xf6, 0xc9, 0xeb, 0xdc, 0x3e, 0xf9, 0xb8, 0x44, 0x09, 0xc9, 0x76, 0xf8, 0x5d, 0x83, 0x67,
	0xd7, 0x78, 0x4e, 0x5d, 0xa5, 0x03, 0x9b, 0xfc, 0x12, 0x12, 0x21, 0x51, 0x7f, 0xab, 0xf6, 0xa2,
	0x55, 0x5c, 0x2c, 0xa1, 0xaf, 0xc0, 0x7a, 0x64, 0x1f, 0x92, 0x05, 0x75, 0x48, 0x1c, 0x59, 0x51,
	0x91, 0x3b, 0x6e, 0x74, 0xfe, 0xd6, 0xe1, 0x24, 0xad, 0x44, 0x3d, 0xe5, 0xbb, 0x9d, 0x4f, 0x20,
	0x47, 0x6d, 0x3e, 0xb2, 0x48, 0xf9, 0xc9, 0x4e, 0x2a, 0x2e, 0xfe, 0xd7, 0x3d, 0xc5, 0x47, 0xf9,
	0x06, 0xe5, 0xf3, 0x65, 0x82, 0xe3, 0xac, 0x3b, 0xd0, 0x0b, 0x97, 0xa3, 0x7e, 0xe8, 0x72, 0xac,
	0xee, 0x5a, 0x8e, 0xdf, 0xc2, 0xf3, 0xad, 0x03, 0x29, 0x10, 0x74, 0x2b, 0x2b, 0x68, 0x23, 0xfb,
	0x18, 0xc6, 0xf0, 0xd1, 0x9e, 0x4e, 0x0f, 0x81, 0xeb, 0xfc, 0x04, 0x90, 0xce, 0xb1, 0x94, 0xce,
	0x7b, 0x39, 0x9d, 0x5b, 0xdb, 0x19, 0x89, 0xe5, 0x3d, 0x3d, 0x52, 0x7f, 0x64, 0x3f, 0xff, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0x3c, 0xf4, 0xac, 0x25, 0x13, 0x0b, 0x00, 0x00,
}
