// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gathergrpc/metricModels.proto

package gathergrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Event struct {
	Unit        string  `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
	Type        string  `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	UpperBound  float32 `protobuf:"fixed32,3,opt,name=upperBound" json:"upperBound,omitempty"`
	LowerBound  float32 `protobuf:"fixed32,4,opt,name=lowerBound" json:"lowerBound,omitempty"`
	UpperStrict bool    `protobuf:"varint,5,opt,name=upperStrict" json:"upperStrict,omitempty"`
	LowerStrict bool    `protobuf:"varint,6,opt,name=lowerStrict" json:"lowerStrict,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Event) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetUpperBound() float32 {
	if m != nil {
		return m.UpperBound
	}
	return 0
}

func (m *Event) GetLowerBound() float32 {
	if m != nil {
		return m.LowerBound
	}
	return 0
}

func (m *Event) GetUpperStrict() bool {
	if m != nil {
		return m.UpperStrict
	}
	return false
}

func (m *Event) GetLowerStrict() bool {
	if m != nil {
		return m.LowerStrict
	}
	return false
}

type MetricData struct {
	Direction string   `protobuf:"bytes,1,opt,name=direction" json:"direction,omitempty"`
	Events    []*Event `protobuf:"bytes,2,rep,name=events" json:"events,omitempty"`
}

func (m *MetricData) Reset()                    { *m = MetricData{} }
func (m *MetricData) String() string            { return proto.CompactTextString(m) }
func (*MetricData) ProtoMessage()               {}
func (*MetricData) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *MetricData) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *MetricData) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Metric struct {
	Id   string        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Data []*MetricData `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *Metric) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Metric) GetData() []*MetricData {
	if m != nil {
		return m.Data
	}
	return nil
}

type Threshold struct {
	Metrics []*Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *Threshold) Reset()                    { *m = Threshold{} }
func (m *Threshold) String() string            { return proto.CompactTextString(m) }
func (*Threshold) ProtoMessage()               {}
func (*Threshold) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *Threshold) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type ThresholdProfile struct {
	Twamp *Threshold `protobuf:"bytes,1,opt,name=twamp" json:"twamp,omitempty"`
}

func (m *ThresholdProfile) Reset()                    { *m = ThresholdProfile{} }
func (m *ThresholdProfile) String() string            { return proto.CompactTextString(m) }
func (*ThresholdProfile) ProtoMessage()               {}
func (*ThresholdProfile) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *ThresholdProfile) GetTwamp() *Threshold {
	if m != nil {
		return m.Twamp
	}
	return nil
}

type ThresholdCrossingResult struct {
	Total             float32 `protobuf:"fixed32,1,opt,name=total" json:"total,omitempty"`
	MinorPercent      float32 `protobuf:"fixed32,2,opt,name=minorPercent" json:"minorPercent,omitempty"`
	MinorRatio        float32 `protobuf:"fixed32,3,opt,name=minorRatio" json:"minorRatio,omitempty"`
	MinorThreshold    float32 `protobuf:"fixed32,4,opt,name=minorThreshold" json:"minorThreshold,omitempty"`
	MajorThreshold    float32 `protobuf:"fixed32,5,opt,name=majorThreshold" json:"majorThreshold,omitempty"`
	CriticalRatio     float32 `protobuf:"fixed32,6,opt,name=criticalRatio" json:"criticalRatio,omitempty"`
	CriticalThreshold float32 `protobuf:"fixed32,7,opt,name=criticalThreshold" json:"criticalThreshold,omitempty"`
	CriticalPercent   float32 `protobuf:"fixed32,8,opt,name=criticalPercent" json:"criticalPercent,omitempty"`
	MajorPercent      float32 `protobuf:"fixed32,9,opt,name=majorPercent" json:"majorPercent,omitempty"`
	MajorRatio        float32 `protobuf:"fixed32,10,opt,name=majorRatio" json:"majorRatio,omitempty"`
}

func (m *ThresholdCrossingResult) Reset()                    { *m = ThresholdCrossingResult{} }
func (m *ThresholdCrossingResult) String() string            { return proto.CompactTextString(m) }
func (*ThresholdCrossingResult) ProtoMessage()               {}
func (*ThresholdCrossingResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *ThresholdCrossingResult) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ThresholdCrossingResult) GetMinorPercent() float32 {
	if m != nil {
		return m.MinorPercent
	}
	return 0
}

func (m *ThresholdCrossingResult) GetMinorRatio() float32 {
	if m != nil {
		return m.MinorRatio
	}
	return 0
}

func (m *ThresholdCrossingResult) GetMinorThreshold() float32 {
	if m != nil {
		return m.MinorThreshold
	}
	return 0
}

func (m *ThresholdCrossingResult) GetMajorThreshold() float32 {
	if m != nil {
		return m.MajorThreshold
	}
	return 0
}

func (m *ThresholdCrossingResult) GetCriticalRatio() float32 {
	if m != nil {
		return m.CriticalRatio
	}
	return 0
}

func (m *ThresholdCrossingResult) GetCriticalThreshold() float32 {
	if m != nil {
		return m.CriticalThreshold
	}
	return 0
}

func (m *ThresholdCrossingResult) GetCriticalPercent() float32 {
	if m != nil {
		return m.CriticalPercent
	}
	return 0
}

func (m *ThresholdCrossingResult) GetMajorPercent() float32 {
	if m != nil {
		return m.MajorPercent
	}
	return 0
}

func (m *ThresholdCrossingResult) GetMajorRatio() float32 {
	if m != nil {
		return m.MajorRatio
	}
	return 0
}

type ThresholdCrossing struct {
	Timestamp string                   `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Result    *ThresholdCrossingResult `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *ThresholdCrossing) Reset()                    { *m = ThresholdCrossing{} }
func (m *ThresholdCrossing) String() string            { return proto.CompactTextString(m) }
func (*ThresholdCrossing) ProtoMessage()               {}
func (*ThresholdCrossing) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *ThresholdCrossing) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ThresholdCrossing) GetResult() *ThresholdCrossingResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type ThresholdCrossingResponse struct {
	Data []*ThresholdCrossing `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *ThresholdCrossingResponse) Reset()                    { *m = ThresholdCrossingResponse{} }
func (m *ThresholdCrossingResponse) String() string            { return proto.CompactTextString(m) }
func (*ThresholdCrossingResponse) ProtoMessage()               {}
func (*ThresholdCrossingResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *ThresholdCrossingResponse) GetData() []*ThresholdCrossing {
	if m != nil {
		return m.Data
	}
	return nil
}

type ThresholdCrossingRequest struct {
	ThresholdProfileName string `protobuf:"bytes,1,opt,name=thresholdProfileName" json:"thresholdProfileName,omitempty"`
	Interval             string `protobuf:"bytes,2,opt,name=interval" json:"interval,omitempty"`
	Tenant               string `protobuf:"bytes,3,opt,name=tenant" json:"tenant,omitempty"`
	Domain               string `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty"`
	Granularity          string `protobuf:"bytes,5,opt,name=granularity" json:"granularity,omitempty"`
	ObjectType           string `protobuf:"bytes,6,opt,name=objectType" json:"objectType,omitempty"`
	Direction            string `protobuf:"bytes,7,opt,name=direction" json:"direction,omitempty"`
	Metric               string `protobuf:"bytes,8,opt,name=metric" json:"metric,omitempty"`
}

func (m *ThresholdCrossingRequest) Reset()                    { *m = ThresholdCrossingRequest{} }
func (m *ThresholdCrossingRequest) String() string            { return proto.CompactTextString(m) }
func (*ThresholdCrossingRequest) ProtoMessage()               {}
func (*ThresholdCrossingRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *ThresholdCrossingRequest) GetThresholdProfileName() string {
	if m != nil {
		return m.ThresholdProfileName
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetGranularity() string {
	if m != nil {
		return m.Granularity
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "gathergrpc.Event")
	proto.RegisterType((*MetricData)(nil), "gathergrpc.MetricData")
	proto.RegisterType((*Metric)(nil), "gathergrpc.Metric")
	proto.RegisterType((*Threshold)(nil), "gathergrpc.Threshold")
	proto.RegisterType((*ThresholdProfile)(nil), "gathergrpc.ThresholdProfile")
	proto.RegisterType((*ThresholdCrossingResult)(nil), "gathergrpc.ThresholdCrossingResult")
	proto.RegisterType((*ThresholdCrossing)(nil), "gathergrpc.ThresholdCrossing")
	proto.RegisterType((*ThresholdCrossingResponse)(nil), "gathergrpc.ThresholdCrossingResponse")
	proto.RegisterType((*ThresholdCrossingRequest)(nil), "gathergrpc.ThresholdCrossingRequest")
}

func init() { proto.RegisterFile("gathergrpc/metricModels.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x5f, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0x95, 0x6d, 0xb3, 0xed, 0x4e, 0xa0, 0x50, 0xab, 0x94, 0x05, 0x51, 0x14, 0x2d, 0x08,
	0x05, 0xa8, 0x8a, 0x08, 0x4f, 0x88, 0x07, 0x24, 0x28, 0x8f, 0xad, 0x2a, 0x53, 0x0e, 0xe0, 0xee,
	0x9a, 0xd4, 0xd5, 0xc6, 0x5e, 0xbc, 0x93, 0x56, 0x3d, 0x00, 0x17, 0xe0, 0x2a, 0x5c, 0x10, 0x79,
	0xec, 0xfd, 0x93, 0x34, 0xe2, 0x2d, 0xf3, 0xf3, 0xe7, 0xd9, 0x19, 0x7f, 0x93, 0x81, 0x83, 0x99,
	0xc0, 0x4b, 0x69, 0x67, 0xb6, 0xca, 0xdf, 0xcd, 0x25, 0x5a, 0x95, 0x9f, 0x98, 0x42, 0x96, 0xf5,
	0x51, 0x65, 0x0d, 0x1a, 0x06, 0xdd, 0x71, 0xf6, 0x77, 0x00, 0xc3, 0x6f, 0xd7, 0x52, 0x23, 0x63,
	0xb0, 0xb9, 0xd0, 0x0a, 0xd3, 0xc1, 0x78, 0x30, 0x49, 0x38, 0xfd, 0x76, 0x0c, 0x6f, 0x2b, 0x99,
	0x46, 0x9e, 0xb9, 0xdf, 0xec, 0x39, 0xc0, 0xa2, 0xaa, 0xa4, 0xfd, 0x62, 0x16, 0xba, 0x48, 0x37,
	0xc6, 0x83, 0x49, 0xc4, 0x7b, 0xc4, 0x9d, 0x97, 0xe6, 0xa6, 0x39, 0xdf, 0xf4, 0xe7, 0x1d, 0x61,
	0x63, 0x18, 0x91, 0xfa, 0xbb, 0xab, 0x0b, 0xd3, 0xe1, 0x78, 0x30, 0xd9, 0xe6, 0x7d, 0xe4, 0x14,
	0xa4, 0x0f, 0x8a, 0xd8, 0x2b, 0x7a, 0x28, 0xfb, 0x01, 0x70, 0x42, 0x7d, 0x1d, 0x0b, 0x14, 0xec,
	0x19, 0x24, 0x85, 0xb2, 0x32, 0x47, 0x65, 0x74, 0x28, 0xbf, 0x03, 0xec, 0x35, 0xc4, 0xd2, 0x35,
	0x58, 0xa7, 0xd1, 0x78, 0x63, 0x32, 0x9a, 0xee, 0x1e, 0x75, 0xed, 0x1f, 0x51, 0xeb, 0x3c, 0x08,
	0xb2, 0x63, 0x88, 0x7d, 0x5a, 0xb6, 0x03, 0x91, 0x2a, 0x42, 0xae, 0x48, 0x15, 0xec, 0x0d, 0x6c,
	0x16, 0x02, 0x45, 0x48, 0xb1, 0xdf, 0x4f, 0xd1, 0x15, 0xc2, 0x49, 0x93, 0x7d, 0x84, 0xe4, 0xfc,
	0xd2, 0xca, 0xfa, 0xd2, 0x94, 0x05, 0x3b, 0x84, 0x2d, 0xef, 0x40, 0x9d, 0x0e, 0xe8, 0x2e, 0xbb,
	0x7b, 0x97, 0x37, 0x92, 0xec, 0x33, 0x3c, 0x6c, 0xaf, 0x9e, 0x59, 0xf3, 0x53, 0x95, 0x92, 0xbd,
	0x85, 0x21, 0xde, 0x88, 0x79, 0x45, 0xd5, 0x8c, 0xa6, 0x8f, 0xfa, 0xf7, 0x5b, 0x31, 0xf7, 0x9a,
	0xec, 0xf7, 0x06, 0x3c, 0x6e, 0xe1, 0x57, 0x6b, 0xea, 0x5a, 0xe9, 0x19, 0x97, 0xf5, 0xa2, 0x44,
	0xb6, 0x07, 0x43, 0x34, 0x28, 0x4a, 0x4a, 0x14, 0x71, 0x1f, 0xb0, 0x0c, 0xee, 0xcd, 0x95, 0x36,
	0xf6, 0x4c, 0xda, 0x5c, 0x6a, 0x24, 0xab, 0x23, 0xbe, 0xc4, 0x9c, 0xa5, 0x14, 0x73, 0x81, 0xca,
	0x34, 0x96, 0x77, 0x84, 0xbd, 0x82, 0x1d, 0x8a, 0xda, 0x2f, 0x07, 0xdb, 0x57, 0x28, 0xe9, 0xc4,
	0x55, 0x5f, 0x37, 0x0c, 0xba, 0x25, 0xca, 0x5e, 0xc2, 0xfd, 0xdc, 0x2a, 0x54, 0xb9, 0x28, 0xfd,
	0x27, 0x63, 0x92, 0x2d, 0x43, 0x76, 0x08, 0xbb, 0x0d, 0xe8, 0x12, 0x6e, 0x91, 0xf2, 0xee, 0x01,
	0x9b, 0xc0, 0x83, 0x06, 0x36, 0xad, 0x6e, 0x93, 0x76, 0x15, 0xd3, 0x8b, 0xb8, 0x7a, 0x1a, 0x59,
	0x12, 0x5e, 0xa4, 0xc7, 0xe8, 0x45, 0x5c, 0xec, 0xcb, 0x83, 0xf0, 0x22, 0x2d, 0xc9, 0x34, 0xec,
	0xde, 0xb1, 0xc1, 0xcd, 0x29, 0xaa, 0xb9, 0xac, 0xb1, 0x71, 0x33, 0xe1, 0x1d, 0x60, 0x9f, 0x20,
	0xb6, 0x64, 0x14, 0x59, 0x30, 0x9a, 0xbe, 0x58, 0x6b, 0xf4, 0xb2, 0xa7, 0x3c, 0x5c, 0xc9, 0x4e,
	0xe1, 0xc9, 0x3a, 0x49, 0x65, 0x74, 0x2d, 0xd9, 0xfb, 0x30, 0xbc, 0x7e, 0x00, 0x0f, 0xfe, 0x9f,
	0xd7, 0xcf, 0xf0, 0x9f, 0x08, 0xd2, 0x35, 0x09, 0x7f, 0x2d, 0x64, 0x8d, 0x6c, 0x0a, 0x7b, 0xb8,
	0x32, 0xa5, 0xa7, 0x62, 0x2e, 0x43, 0x4b, 0x6b, 0xcf, 0xd8, 0x53, 0xd8, 0x56, 0x1a, 0xa5, 0xbd,
	0x16, 0x65, 0xd8, 0x26, 0x6d, 0xcc, 0xf6, 0x21, 0x46, 0xa9, 0x85, 0x46, 0x1a, 0xad, 0x84, 0x87,
	0xc8, 0xf1, 0xc2, 0xcc, 0x85, 0xd2, 0x34, 0x4e, 0x09, 0x0f, 0x91, 0xdb, 0x0f, 0x33, 0x2b, 0xf4,
	0xa2, 0x14, 0x56, 0xe1, 0x2d, 0xcd, 0x50, 0xc2, 0xfb, 0xc8, 0xd9, 0x63, 0x2e, 0xae, 0x64, 0x8e,
	0xe7, 0x6e, 0x7b, 0xc5, 0x24, 0xe8, 0x91, 0xe5, 0x8d, 0xb1, 0xb5, 0xba, 0x31, 0xf6, 0x21, 0xf6,
	0x7f, 0x48, 0x9a, 0x90, 0x84, 0x87, 0xe8, 0x22, 0xa6, 0xf5, 0xf9, 0xe1, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8c, 0x18, 0x3a, 0x21, 0x5f, 0x05, 0x00, 0x00,
}
