// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gathergrpc/metricModels.proto

package gathergrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ThresholdCrossing struct {
	Timestamp string             `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Result    map[string]float32 `protobuf:"bytes,2,rep,name=result" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
}

func (m *ThresholdCrossing) Reset()                    { *m = ThresholdCrossing{} }
func (m *ThresholdCrossing) String() string            { return proto.CompactTextString(m) }
func (*ThresholdCrossing) ProtoMessage()               {}
func (*ThresholdCrossing) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *ThresholdCrossing) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ThresholdCrossing) GetResult() map[string]float32 {
	if m != nil {
		return m.Result
	}
	return nil
}

type FormattedThresholdCrossing struct {
	Timestamp string                   `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Result    *google_protobuf1.Struct `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *FormattedThresholdCrossing) Reset()                    { *m = FormattedThresholdCrossing{} }
func (m *FormattedThresholdCrossing) String() string            { return proto.CompactTextString(m) }
func (*FormattedThresholdCrossing) ProtoMessage()               {}
func (*FormattedThresholdCrossing) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *FormattedThresholdCrossing) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *FormattedThresholdCrossing) GetResult() *google_protobuf1.Struct {
	if m != nil {
		return m.Result
	}
	return nil
}

type ThresholdCrossingResponse struct {
	Data []*FormattedThresholdCrossing `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *ThresholdCrossingResponse) Reset()                    { *m = ThresholdCrossingResponse{} }
func (m *ThresholdCrossingResponse) String() string            { return proto.CompactTextString(m) }
func (*ThresholdCrossingResponse) ProtoMessage()               {}
func (*ThresholdCrossingResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *ThresholdCrossingResponse) GetData() []*FormattedThresholdCrossing {
	if m != nil {
		return m.Data
	}
	return nil
}

type ThresholdCrossingRequest struct {
	// ISO-8601 Intervals
	Interval string `protobuf:"bytes,1,opt,name=interval" json:"interval,omitempty"`
	Tenant   string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
	Domain   string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	// ISO-8601 period combination
	Granularity        string `protobuf:"bytes,4,opt,name=granularity" json:"granularity,omitempty"`
	ObjectType         string `protobuf:"bytes,5,opt,name=objectType" json:"objectType,omitempty"`
	Direction          string `protobuf:"bytes,6,opt,name=direction" json:"direction,omitempty"`
	Metric             string `protobuf:"bytes,7,opt,name=metric" json:"metric,omitempty"`
	ThresholdProfileId string `protobuf:"bytes,8,opt,name=thresholdProfileId" json:"thresholdProfileId,omitempty"`
	Vendor             string `protobuf:"bytes,9,opt,name=vendor" json:"vendor,omitempty"`
	Timeout            int32  `protobuf:"varint,10,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *ThresholdCrossingRequest) Reset()                    { *m = ThresholdCrossingRequest{} }
func (m *ThresholdCrossingRequest) String() string            { return proto.CompactTextString(m) }
func (*ThresholdCrossingRequest) ProtoMessage()               {}
func (*ThresholdCrossingRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *ThresholdCrossingRequest) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetGranularity() string {
	if m != nil {
		return m.Granularity
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetThresholdProfileId() string {
	if m != nil {
		return m.ThresholdProfileId
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *ThresholdCrossingRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type HistogramRequest struct {
	// ISO-8601 Intervals
	Interval string `protobuf:"bytes,1,opt,name=interval" json:"interval,omitempty"`
	Tenant   string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
	Domain   string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	// ISO-8601 period combination
	Granularity        string `protobuf:"bytes,4,opt,name=granularity" json:"granularity,omitempty"`
	Direction          string `protobuf:"bytes,5,opt,name=direction" json:"direction,omitempty"`
	Metric             string `protobuf:"bytes,6,opt,name=metric" json:"metric,omitempty"`
	GranularityBuckets int32  `protobuf:"varint,7,opt,name=granularityBuckets" json:"granularityBuckets,omitempty"`
	Resolution         int32  `protobuf:"varint,8,opt,name=resolution" json:"resolution,omitempty"`
	Vendor             string `protobuf:"bytes,9,opt,name=vendor" json:"vendor,omitempty"`
	Timeout            int32  `protobuf:"varint,10,opt,name=timeout" json:"timeout,omitempty"`
}

func (m *HistogramRequest) Reset()                    { *m = HistogramRequest{} }
func (m *HistogramRequest) String() string            { return proto.CompactTextString(m) }
func (*HistogramRequest) ProtoMessage()               {}
func (*HistogramRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *HistogramRequest) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *HistogramRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *HistogramRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *HistogramRequest) GetGranularity() string {
	if m != nil {
		return m.Granularity
	}
	return ""
}

func (m *HistogramRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *HistogramRequest) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *HistogramRequest) GetGranularityBuckets() int32 {
	if m != nil {
		return m.GranularityBuckets
	}
	return 0
}

func (m *HistogramRequest) GetResolution() int32 {
	if m != nil {
		return m.Resolution
	}
	return 0
}

func (m *HistogramRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *HistogramRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type HistogramBuckets struct {
	Breaks []float32 `protobuf:"fixed32,1,rep,packed,name=breaks" json:"breaks,omitempty"`
	Counts []float32 `protobuf:"fixed32,2,rep,packed,name=counts" json:"counts,omitempty"`
}

func (m *HistogramBuckets) Reset()                    { *m = HistogramBuckets{} }
func (m *HistogramBuckets) String() string            { return proto.CompactTextString(m) }
func (*HistogramBuckets) ProtoMessage()               {}
func (*HistogramBuckets) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *HistogramBuckets) GetBreaks() []float32 {
	if m != nil {
		return m.Breaks
	}
	return nil
}

func (m *HistogramBuckets) GetCounts() []float32 {
	if m != nil {
		return m.Counts
	}
	return nil
}

type HistogramResult struct {
	ThresholdBuckets *HistogramBuckets `protobuf:"bytes,1,opt,name=thresholdBuckets" json:"thresholdBuckets,omitempty"`
}

func (m *HistogramResult) Reset()                    { *m = HistogramResult{} }
func (m *HistogramResult) String() string            { return proto.CompactTextString(m) }
func (*HistogramResult) ProtoMessage()               {}
func (*HistogramResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *HistogramResult) GetThresholdBuckets() *HistogramBuckets {
	if m != nil {
		return m.ThresholdBuckets
	}
	return nil
}

type Histogram struct {
	Timestamp string           `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Result    *HistogramResult `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *Histogram) Reset()                    { *m = Histogram{} }
func (m *Histogram) String() string            { return proto.CompactTextString(m) }
func (*Histogram) ProtoMessage()               {}
func (*Histogram) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *Histogram) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Histogram) GetResult() *HistogramResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type HistogramResponse struct {
	Data []*Histogram `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *HistogramResponse) Reset()                    { *m = HistogramResponse{} }
func (m *HistogramResponse) String() string            { return proto.CompactTextString(m) }
func (*HistogramResponse) ProtoMessage()               {}
func (*HistogramResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *HistogramResponse) GetData() []*Histogram {
	if m != nil {
		return m.Data
	}
	return nil
}

type ThresholdCrossingByMonitoredObjectResponse struct {
	Result *google_protobuf1.Struct `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ThresholdCrossingByMonitoredObjectResponse) Reset() {
	*m = ThresholdCrossingByMonitoredObjectResponse{}
}
func (m *ThresholdCrossingByMonitoredObjectResponse) String() string {
	return proto.CompactTextString(m)
}
func (*ThresholdCrossingByMonitoredObjectResponse) ProtoMessage() {}
func (*ThresholdCrossingByMonitoredObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{9}
}

func (m *ThresholdCrossingByMonitoredObjectResponse) GetResult() *google_protobuf1.Struct {
	if m != nil {
		return m.Result
	}
	return nil
}

type RawMetricsRequest struct {
	// ISO-8601 Intervals
	Interval          string `protobuf:"bytes,1,opt,name=interval" json:"interval,omitempty"`
	Tenant            string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
	Direction         string `protobuf:"bytes,3,opt,name=direction" json:"direction,omitempty"`
	Metric            string `protobuf:"bytes,4,opt,name=metric" json:"metric,omitempty"`
	ObjectType        string `protobuf:"bytes,5,opt,name=objectType" json:"objectType,omitempty"`
	MonitoredObjectId string `protobuf:"bytes,6,opt,name=monitoredObjectId" json:"monitoredObjectId,omitempty"`
	Timeout           int32  `protobuf:"varint,10,opt,name=timeout" json:"timeout,omitempty"`
	Granularity       string `protobuf:"bytes,11,opt,name=granularity" json:"granularity,omitempty"`
}

func (m *RawMetricsRequest) Reset()                    { *m = RawMetricsRequest{} }
func (m *RawMetricsRequest) String() string            { return proto.CompactTextString(m) }
func (*RawMetricsRequest) ProtoMessage()               {}
func (*RawMetricsRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *RawMetricsRequest) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *RawMetricsRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *RawMetricsRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *RawMetricsRequest) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *RawMetricsRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *RawMetricsRequest) GetMonitoredObjectId() string {
	if m != nil {
		return m.MonitoredObjectId
	}
	return ""
}

func (m *RawMetricsRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RawMetricsRequest) GetGranularity() string {
	if m != nil {
		return m.Granularity
	}
	return ""
}

type RawMetricsResponse struct {
	Result *google_protobuf1.Struct `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *RawMetricsResponse) Reset()                    { *m = RawMetricsResponse{} }
func (m *RawMetricsResponse) String() string            { return proto.CompactTextString(m) }
func (*RawMetricsResponse) ProtoMessage()               {}
func (*RawMetricsResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *RawMetricsResponse) GetResult() *google_protobuf1.Struct {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*ThresholdCrossing)(nil), "gathergrpc.ThresholdCrossing")
	proto.RegisterType((*FormattedThresholdCrossing)(nil), "gathergrpc.FormattedThresholdCrossing")
	proto.RegisterType((*ThresholdCrossingResponse)(nil), "gathergrpc.ThresholdCrossingResponse")
	proto.RegisterType((*ThresholdCrossingRequest)(nil), "gathergrpc.ThresholdCrossingRequest")
	proto.RegisterType((*HistogramRequest)(nil), "gathergrpc.HistogramRequest")
	proto.RegisterType((*HistogramBuckets)(nil), "gathergrpc.HistogramBuckets")
	proto.RegisterType((*HistogramResult)(nil), "gathergrpc.HistogramResult")
	proto.RegisterType((*Histogram)(nil), "gathergrpc.Histogram")
	proto.RegisterType((*HistogramResponse)(nil), "gathergrpc.HistogramResponse")
	proto.RegisterType((*ThresholdCrossingByMonitoredObjectResponse)(nil), "gathergrpc.ThresholdCrossingByMonitoredObjectResponse")
	proto.RegisterType((*RawMetricsRequest)(nil), "gathergrpc.RawMetricsRequest")
	proto.RegisterType((*RawMetricsResponse)(nil), "gathergrpc.RawMetricsResponse")
}

func init() { proto.RegisterFile("gathergrpc/metricModels.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0x26, 0x6d, 0x26, 0x07, 0x9a, 0x15, 0x94, 0x25, 0x14, 0x14, 0xf9, 0x80, 0x52,
	0x84, 0x1c, 0xa9, 0xbd, 0x40, 0x0f, 0x48, 0x14, 0x15, 0xb5, 0x87, 0x0a, 0xb4, 0x54, 0xe2, 0x80,
	0x40, 0xda, 0xd8, 0x5b, 0xd7, 0xc4, 0xf6, 0x86, 0xdd, 0x71, 0x50, 0x7e, 0x01, 0x3f, 0x87, 0x2b,
	0x47, 0x7e, 0x1a, 0xf2, 0xae, 0x93, 0x38, 0x5f, 0x2a, 0x94, 0x03, 0x37, 0xcf, 0x87, 0xe7, 0xed,
	0xbc, 0x7d, 0x6f, 0xe1, 0x51, 0xc4, 0xf1, 0x5a, 0xa8, 0x48, 0x8d, 0x82, 0x7e, 0x2a, 0x50, 0xc5,
	0xc1, 0x85, 0x0c, 0x45, 0xa2, 0xfd, 0x91, 0x92, 0x28, 0x09, 0xcc, 0xcb, 0x9d, 0xfd, 0x48, 0xca,
	0x28, 0x11, 0x7d, 0x53, 0x19, 0xe4, 0x57, 0x7d, 0x8d, 0x2a, 0x0f, 0xd0, 0x76, 0x7a, 0x3f, 0x1c,
	0x68, 0x5f, 0x5e, 0x2b, 0xa1, 0xaf, 0x65, 0x12, 0xbe, 0x56, 0x52, 0xeb, 0x38, 0x8b, 0xc8, 0x3e,
	0x34, 0x31, 0x4e, 0x85, 0x46, 0x9e, 0x8e, 0xa8, 0xd3, 0x75, 0x7a, 0x4d, 0x36, 0x4f, 0x90, 0x57,
	0xd0, 0x50, 0x42, 0xe7, 0x09, 0x52, 0xb7, 0x5b, 0xeb, 0xb5, 0x0e, 0x0f, 0xfc, 0x39, 0x9c, 0xbf,
	0x32, 0xcc, 0x67, 0xa6, 0xf7, 0x34, 0x43, 0x35, 0x61, 0xe5, 0x8f, 0x9d, 0x17, 0xd0, 0xaa, 0xa4,
	0xc9, 0x2e, 0xd4, 0x86, 0x62, 0x52, 0x22, 0x15, 0x9f, 0xe4, 0x2e, 0xd4, 0xc7, 0x3c, 0xc9, 0x05,
	0x75, 0xbb, 0x4e, 0xcf, 0x65, 0x36, 0x38, 0x76, 0x9f, 0x3b, 0xde, 0x10, 0x3a, 0x6f, 0xa4, 0x4a,
	0x39, 0xa2, 0x08, 0xff, 0xf6, 0xe4, 0xfd, 0xca, 0xc9, 0x9d, 0x5e, 0xeb, 0xf0, 0xbe, 0x6f, 0xc9,
	0xf1, 0xa7, 0xe4, 0xf8, 0xef, 0x0d, 0x39, 0xd3, 0x73, 0x7a, 0x1f, 0xe0, 0xc1, 0x0a, 0x06, 0x13,
	0x7a, 0x24, 0x33, 0x2d, 0xc8, 0x31, 0x6c, 0x85, 0x1c, 0x39, 0x75, 0x0c, 0x0b, 0x4f, 0xaa, 0x2c,
	0x6c, 0x3e, 0x21, 0x33, 0xff, 0x78, 0xbf, 0x5c, 0xa0, 0x6b, 0x26, 0x7f, 0xcd, 0x85, 0x46, 0xd2,
	0x81, 0x9d, 0x38, 0x43, 0xa1, 0xc6, 0x3c, 0x29, 0x77, 0x98, 0xc5, 0x64, 0x0f, 0x1a, 0x28, 0x32,
	0x9e, 0xd9, 0x15, 0x9a, 0xac, 0x8c, 0x8a, 0x7c, 0x28, 0x53, 0x1e, 0x67, 0xb4, 0x66, 0xf3, 0x36,
	0x22, 0x5d, 0x68, 0x45, 0x8a, 0x67, 0x79, 0xc2, 0x55, 0x8c, 0x13, 0xba, 0x65, 0x8a, 0xd5, 0x14,
	0x79, 0x0c, 0x20, 0x07, 0x5f, 0x44, 0x80, 0x97, 0x93, 0x91, 0xa0, 0x75, 0xd3, 0x50, 0xc9, 0x14,
	0x94, 0x86, 0xb1, 0x12, 0x01, 0xc6, 0x32, 0xa3, 0x0d, 0x4b, 0xe9, 0x2c, 0x51, 0xe0, 0x5a, 0x01,
	0xd2, 0x6d, 0x8b, 0x6b, 0x23, 0xe2, 0x03, 0xc1, 0xe9, 0x7e, 0xef, 0x94, 0xbc, 0x8a, 0x13, 0x71,
	0x1e, 0xd2, 0x1d, 0xd3, 0xb3, 0xa6, 0x52, 0xcc, 0x19, 0x8b, 0x2c, 0x94, 0x8a, 0x36, 0xed, 0x1c,
	0x1b, 0x11, 0x0a, 0xdb, 0xc5, 0xfd, 0xc9, 0x1c, 0x29, 0x74, 0x9d, 0x5e, 0x9d, 0x4d, 0x43, 0xef,
	0xa7, 0x0b, 0xbb, 0x67, 0xb1, 0x46, 0x19, 0x29, 0x9e, 0xfe, 0x1f, 0xea, 0x16, 0xa8, 0xa9, 0x6f,
	0xa6, 0xa6, 0xb1, 0x4c, 0x4d, 0x65, 0xc8, 0x49, 0x1e, 0x0c, 0x05, 0x6a, 0x43, 0x5f, 0x9d, 0xad,
	0xa9, 0x14, 0x17, 0xa4, 0x84, 0x96, 0x49, 0x6e, 0x60, 0x76, 0x4c, 0x5f, 0x25, 0x73, 0x0b, 0xea,
	0x4e, 0x2a, 0xcc, 0x4d, 0x51, 0xf6, 0xa0, 0x31, 0x50, 0x82, 0x0f, 0xb5, 0xd1, 0xb3, 0xcb, 0xca,
	0xa8, 0xc8, 0x07, 0x32, 0xcf, 0x50, 0x1b, 0xb7, 0xbb, 0xac, 0x8c, 0xbc, 0x8f, 0x70, 0xa7, 0xc2,
	0x7e, 0xe1, 0x16, 0x72, 0x06, 0xbb, 0xb3, 0x9b, 0x9d, 0xae, 0xe5, 0x18, 0xa3, 0xed, 0x57, 0xcd,
	0xb1, 0x0c, 0xcd, 0x56, 0xfe, 0xf2, 0x3e, 0x43, 0x73, 0xd6, 0x75, 0x83, 0xa7, 0x8f, 0x96, 0x3c,
	0xfd, 0x70, 0x2d, 0x94, 0x3d, 0xe1, 0xcc, 0xd7, 0x2f, 0xa1, 0x5d, 0x2d, 0x59, 0x3f, 0x1f, 0x2c,
	0xf8, 0xf9, 0xde, 0xfa, 0x39, 0xd6, 0xbe, 0x9f, 0xe0, 0xe9, 0x8a, 0x7b, 0x4f, 0x26, 0x17, 0x32,
	0x8b, 0x51, 0x2a, 0x11, 0xbe, 0x35, 0xee, 0x99, 0x0d, 0x9e, 0x3f, 0x3b, 0xce, 0x9f, 0x3d, 0x3b,
	0xdf, 0x5d, 0x68, 0x33, 0xfe, 0xed, 0xc2, 0xe8, 0x45, 0xff, 0x8b, 0xb6, 0x17, 0x14, 0x5a, 0xdb,
	0xac, 0xd0, 0xad, 0x05, 0x85, 0xde, 0xf4, 0x24, 0x3c, 0x83, 0x76, 0xba, 0xb8, 0xeb, 0x79, 0x58,
	0x8a, 0x7c, 0xb5, 0xb0, 0x59, 0x87, 0xcb, 0x0e, 0x6b, 0xad, 0x38, 0xcc, 0x3b, 0x05, 0x52, 0x25,
	0xe2, 0x96, 0x84, 0x0e, 0x1a, 0xa6, 0x70, 0xf4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x70, 0xb2,
	0x96, 0x38, 0x07, 0x00, 0x00,
}
