// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gathergrpc/tenantModels.proto

package gathergrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MonitoredObject_MonitoredObjectType int32

const (
	MonitoredObject_MO_UNKNOWN MonitoredObject_MonitoredObjectType = 0
	MonitoredObject_TWAMP      MonitoredObject_MonitoredObjectType = 1
)

var MonitoredObject_MonitoredObjectType_name = map[int32]string{
	0: "MO_UNKNOWN",
	1: "TWAMP",
}
var MonitoredObject_MonitoredObjectType_value = map[string]int32{
	"MO_UNKNOWN": 0,
	"TWAMP":      1,
}

func (x MonitoredObject_MonitoredObjectType) String() string {
	return proto.EnumName(MonitoredObject_MonitoredObjectType_name, int32(x))
}
func (MonitoredObject_MonitoredObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{22, 0}
}

type MonitoredObject_DeviceType int32

const (
	MonitoredObject_DT_UNKNOWN    MonitoredObject_DeviceType = 0
	MonitoredObject_ACCEDIAN_NID  MonitoredObject_DeviceType = 1
	MonitoredObject_ACCEDIAN_VNID MonitoredObject_DeviceType = 2
)

var MonitoredObject_DeviceType_name = map[int32]string{
	0: "DT_UNKNOWN",
	1: "ACCEDIAN_NID",
	2: "ACCEDIAN_VNID",
}
var MonitoredObject_DeviceType_value = map[string]int32{
	"DT_UNKNOWN":    0,
	"ACCEDIAN_NID":  1,
	"ACCEDIAN_VNID": 2,
}

func (x MonitoredObject_DeviceType) String() string {
	return proto.EnumName(MonitoredObject_DeviceType_name, int32(x))
}
func (MonitoredObject_DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{22, 1}
}

// TenantDomain - model for a Domain for a single Tenant.
type TenantDomain struct {
	TenantId              string   `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	Datatype              string   `protobuf:"bytes,2,opt,name=datatype" json:"datatype,omitempty"`
	Name                  string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Color                 string   `protobuf:"bytes,4,opt,name=color" json:"color,omitempty"`
	CreatedTimestamp      int64    `protobuf:"varint,5,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp int64    `protobuf:"varint,6,opt,name=lastModifiedTimestamp" json:"lastModifiedTimestamp,omitempty"`
	ThresholdProfileSet   []string `protobuf:"bytes,7,rep,name=thresholdProfileSet" json:"thresholdProfileSet,omitempty"`
}

func (m *TenantDomain) Reset()                    { *m = TenantDomain{} }
func (m *TenantDomain) String() string            { return proto.CompactTextString(m) }
func (*TenantDomain) ProtoMessage()               {}
func (*TenantDomain) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *TenantDomain) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *TenantDomain) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

func (m *TenantDomain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TenantDomain) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *TenantDomain) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *TenantDomain) GetLastModifiedTimestamp() int64 {
	if m != nil {
		return m.LastModifiedTimestamp
	}
	return 0
}

func (m *TenantDomain) GetThresholdProfileSet() []string {
	if m != nil {
		return m.ThresholdProfileSet
	}
	return nil
}

// TenantDomainRequest - wrapper for requests that involve a Tenant Domain
type TenantDomainRequest struct {
	XId  string        `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string        `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *TenantDomain `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *TenantDomainRequest) Reset()                    { *m = TenantDomainRequest{} }
func (m *TenantDomainRequest) String() string            { return proto.CompactTextString(m) }
func (*TenantDomainRequest) ProtoMessage()               {}
func (*TenantDomainRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *TenantDomainRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *TenantDomainRequest) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *TenantDomainRequest) GetData() *TenantDomain {
	if m != nil {
		return m.Data
	}
	return nil
}

// TenantDomainResponse - wrapper for responses that involve a Tenant Domain
type TenantDomainResponse struct {
	XId  string        `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string        `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *TenantDomain `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *TenantDomainResponse) Reset()                    { *m = TenantDomainResponse{} }
func (m *TenantDomainResponse) String() string            { return proto.CompactTextString(m) }
func (*TenantDomainResponse) ProtoMessage()               {}
func (*TenantDomainResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *TenantDomainResponse) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *TenantDomainResponse) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *TenantDomainResponse) GetData() *TenantDomain {
	if m != nil {
		return m.Data
	}
	return nil
}

// TenantDomainListResponse - a wrapper for a list of TenantDomain objects that
// are returned as a response to a request..
type TenantDomainListResponse struct {
	Data []*TenantDomainResponse `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *TenantDomainListResponse) Reset()                    { *m = TenantDomainListResponse{} }
func (m *TenantDomainListResponse) String() string            { return proto.CompactTextString(m) }
func (*TenantDomainListResponse) ProtoMessage()               {}
func (*TenantDomainListResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *TenantDomainListResponse) GetData() []*TenantDomainResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

// TenantDomainIdRequest - wrapper for requests that involve a Tenant Domain,
// but only require the domainID to complete the request.
type TenantDomainIdRequest struct {
	TenantId string `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	DomainId string `protobuf:"bytes,2,opt,name=domainId" json:"domainId,omitempty"`
}

func (m *TenantDomainIdRequest) Reset()                    { *m = TenantDomainIdRequest{} }
func (m *TenantDomainIdRequest) String() string            { return proto.CompactTextString(m) }
func (*TenantDomainIdRequest) ProtoMessage()               {}
func (*TenantDomainIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *TenantDomainIdRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *TenantDomainIdRequest) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

// TenantIngestionProfile - model for the singleton object that
// governs what data is displayed for a Tenant.
type TenantIngestionProfile struct {
	TenantId              string                                                `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	Datatype              string                                                `protobuf:"bytes,2,opt,name=datatype" json:"datatype,omitempty"`
	Metrics               map[string]*TenantIngestionProfile_MonitoredObjectMap `protobuf:"bytes,3,rep,name=metrics" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedTimestamp      int64                                                 `protobuf:"varint,4,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp int64                                                 `protobuf:"varint,5,opt,name=lastModifiedTimestamp" json:"lastModifiedTimestamp,omitempty"`
}

func (m *TenantIngestionProfile) Reset()                    { *m = TenantIngestionProfile{} }
func (m *TenantIngestionProfile) String() string            { return proto.CompactTextString(m) }
func (*TenantIngestionProfile) ProtoMessage()               {}
func (*TenantIngestionProfile) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *TenantIngestionProfile) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *TenantIngestionProfile) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

func (m *TenantIngestionProfile) GetMetrics() map[string]*TenantIngestionProfile_MonitoredObjectMap {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *TenantIngestionProfile) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *TenantIngestionProfile) GetLastModifiedTimestamp() int64 {
	if m != nil {
		return m.LastModifiedTimestamp
	}
	return 0
}

type TenantIngestionProfile_MetricMap struct {
	MetricMap map[string]bool `protobuf:"bytes,1,rep,name=metricMap" json:"metricMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *TenantIngestionProfile_MetricMap) Reset()         { *m = TenantIngestionProfile_MetricMap{} }
func (m *TenantIngestionProfile_MetricMap) String() string { return proto.CompactTextString(m) }
func (*TenantIngestionProfile_MetricMap) ProtoMessage()    {}
func (*TenantIngestionProfile_MetricMap) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{5, 0}
}

func (m *TenantIngestionProfile_MetricMap) GetMetricMap() map[string]bool {
	if m != nil {
		return m.MetricMap
	}
	return nil
}

type TenantIngestionProfile_MonitoredObjectMap struct {
	MonitoredObjectMap map[string]*TenantIngestionProfile_MetricMap `protobuf:"bytes,1,rep,name=monitoredObjectMap" json:"monitoredObjectMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TenantIngestionProfile_MonitoredObjectMap) Reset() {
	*m = TenantIngestionProfile_MonitoredObjectMap{}
}
func (m *TenantIngestionProfile_MonitoredObjectMap) String() string { return proto.CompactTextString(m) }
func (*TenantIngestionProfile_MonitoredObjectMap) ProtoMessage()    {}
func (*TenantIngestionProfile_MonitoredObjectMap) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{5, 1}
}

func (m *TenantIngestionProfile_MonitoredObjectMap) GetMonitoredObjectMap() map[string]*TenantIngestionProfile_MetricMap {
	if m != nil {
		return m.MonitoredObjectMap
	}
	return nil
}

// TenantIngestionProfileRequest - wrapper for requests that involve the
// Tenant Ingestion Profile
type TenantIngestionProfileRequest struct {
	XId  string                  `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string                  `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *TenantIngestionProfile `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *TenantIngestionProfileRequest) Reset()                    { *m = TenantIngestionProfileRequest{} }
func (m *TenantIngestionProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*TenantIngestionProfileRequest) ProtoMessage()               {}
func (*TenantIngestionProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *TenantIngestionProfileRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *TenantIngestionProfileRequest) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *TenantIngestionProfileRequest) GetData() *TenantIngestionProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

// TenantIngestionProfileResponse - wrapper to provide a Tenant Ingestion Profile
// in a response.
type TenantIngestionProfileResponse struct {
	XId  string                  `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string                  `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *TenantIngestionProfile `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *TenantIngestionProfileResponse) Reset()                    { *m = TenantIngestionProfileResponse{} }
func (m *TenantIngestionProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*TenantIngestionProfileResponse) ProtoMessage()               {}
func (*TenantIngestionProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *TenantIngestionProfileResponse) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *TenantIngestionProfileResponse) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *TenantIngestionProfileResponse) GetData() *TenantIngestionProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

type TenantIngestionProfileIdRequest struct {
	TenantId           string `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	IngestionProfileId string `protobuf:"bytes,2,opt,name=ingestionProfileId" json:"ingestionProfileId,omitempty"`
}

func (m *TenantIngestionProfileIdRequest) Reset()                    { *m = TenantIngestionProfileIdRequest{} }
func (m *TenantIngestionProfileIdRequest) String() string            { return proto.CompactTextString(m) }
func (*TenantIngestionProfileIdRequest) ProtoMessage()               {}
func (*TenantIngestionProfileIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *TenantIngestionProfileIdRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *TenantIngestionProfileIdRequest) GetIngestionProfileId() string {
	if m != nil {
		return m.IngestionProfileId
	}
	return ""
}

// TenantThresholdProfile
type TenantThresholdProfile struct {
	TenantId              string             `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	Datatype              string             `protobuf:"bytes,2,opt,name=datatype" json:"datatype,omitempty"`
	Thresholds            []*TenantThreshold `protobuf:"bytes,3,rep,name=thresholds" json:"thresholds,omitempty"`
	CreatedTimestamp      int64              `protobuf:"varint,4,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp int64              `protobuf:"varint,5,opt,name=lastModifiedTimestamp" json:"lastModifiedTimestamp,omitempty"`
}

func (m *TenantThresholdProfile) Reset()                    { *m = TenantThresholdProfile{} }
func (m *TenantThresholdProfile) String() string            { return proto.CompactTextString(m) }
func (*TenantThresholdProfile) ProtoMessage()               {}
func (*TenantThresholdProfile) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *TenantThresholdProfile) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *TenantThresholdProfile) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

func (m *TenantThresholdProfile) GetThresholds() []*TenantThreshold {
	if m != nil {
		return m.Thresholds
	}
	return nil
}

func (m *TenantThresholdProfile) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *TenantThresholdProfile) GetLastModifiedTimestamp() int64 {
	if m != nil {
		return m.LastModifiedTimestamp
	}
	return 0
}

// TenantThreshold
type TenantThreshold struct {
	Metrics    []*TenantMetric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
	ObjectType string          `protobuf:"bytes,2,opt,name=objectType" json:"objectType,omitempty"`
}

func (m *TenantThreshold) Reset()                    { *m = TenantThreshold{} }
func (m *TenantThreshold) String() string            { return proto.CompactTextString(m) }
func (*TenantThreshold) ProtoMessage()               {}
func (*TenantThreshold) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *TenantThreshold) GetMetrics() []*TenantMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *TenantThreshold) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

// TenantMetric
type TenantMetric struct {
	Id   string              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Data []*TenantMetricData `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *TenantMetric) Reset()                    { *m = TenantMetric{} }
func (m *TenantMetric) String() string            { return proto.CompactTextString(m) }
func (*TenantMetric) ProtoMessage()               {}
func (*TenantMetric) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *TenantMetric) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TenantMetric) GetData() []*TenantMetricData {
	if m != nil {
		return m.Data
	}
	return nil
}

// TenantMetricData
type TenantMetricData struct {
	Direction string         `protobuf:"bytes,1,opt,name=direction" json:"direction,omitempty"`
	Events    []*TenantEvent `protobuf:"bytes,2,rep,name=events" json:"events,omitempty"`
}

func (m *TenantMetricData) Reset()                    { *m = TenantMetricData{} }
func (m *TenantMetricData) String() string            { return proto.CompactTextString(m) }
func (*TenantMetricData) ProtoMessage()               {}
func (*TenantMetricData) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *TenantMetricData) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *TenantMetricData) GetEvents() []*TenantEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

// TenantEvent
type TenantEvent struct {
	Unit        string  `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
	Type        string  `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	UpperBound  float32 `protobuf:"fixed32,3,opt,name=upperBound" json:"upperBound,omitempty"`
	LowerBound  float32 `protobuf:"fixed32,4,opt,name=lowerBound" json:"lowerBound,omitempty"`
	UpperStrict bool    `protobuf:"varint,5,opt,name=upperStrict" json:"upperStrict,omitempty"`
	LowerStrict bool    `protobuf:"varint,6,opt,name=lowerStrict" json:"lowerStrict,omitempty"`
}

func (m *TenantEvent) Reset()                    { *m = TenantEvent{} }
func (m *TenantEvent) String() string            { return proto.CompactTextString(m) }
func (*TenantEvent) ProtoMessage()               {}
func (*TenantEvent) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *TenantEvent) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *TenantEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TenantEvent) GetUpperBound() float32 {
	if m != nil {
		return m.UpperBound
	}
	return 0
}

func (m *TenantEvent) GetLowerBound() float32 {
	if m != nil {
		return m.LowerBound
	}
	return 0
}

func (m *TenantEvent) GetUpperStrict() bool {
	if m != nil {
		return m.UpperStrict
	}
	return false
}

func (m *TenantEvent) GetLowerStrict() bool {
	if m != nil {
		return m.LowerStrict
	}
	return false
}

// TenantThresholdProfileRequest - wrapper for requests that involve the
// Tenant Threshold Profile
type TenantThresholdProfileRequest struct {
	XId  string                  `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string                  `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *TenantThresholdProfile `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *TenantThresholdProfileRequest) Reset()                    { *m = TenantThresholdProfileRequest{} }
func (m *TenantThresholdProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*TenantThresholdProfileRequest) ProtoMessage()               {}
func (*TenantThresholdProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *TenantThresholdProfileRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *TenantThresholdProfileRequest) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *TenantThresholdProfileRequest) GetData() *TenantThresholdProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

// TenantIngestionProfileResponse - wrapper to provide a Tenant Ingestion Profile
// in a response.
type TenantThresholdProfileResponse struct {
	XId  string                  `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string                  `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *TenantThresholdProfile `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *TenantThresholdProfileResponse) Reset()                    { *m = TenantThresholdProfileResponse{} }
func (m *TenantThresholdProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*TenantThresholdProfileResponse) ProtoMessage()               {}
func (*TenantThresholdProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *TenantThresholdProfileResponse) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *TenantThresholdProfileResponse) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *TenantThresholdProfileResponse) GetData() *TenantThresholdProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

type TenantThresholdProfileIdRequest struct {
	TenantId           string `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	ThresholdProfileId string `protobuf:"bytes,2,opt,name=thresholdProfileId" json:"thresholdProfileId,omitempty"`
}

func (m *TenantThresholdProfileIdRequest) Reset()         { *m = TenantThresholdProfileIdRequest{} }
func (m *TenantThresholdProfileIdRequest) String() string { return proto.CompactTextString(m) }
func (*TenantThresholdProfileIdRequest) ProtoMessage()    {}
func (*TenantThresholdProfileIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{16}
}

func (m *TenantThresholdProfileIdRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *TenantThresholdProfileIdRequest) GetThresholdProfileId() string {
	if m != nil {
		return m.ThresholdProfileId
	}
	return ""
}

// TenantUser - model for a User that is scoped to a single Tenant.
type TenantUser struct {
	TenantId              string    `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	Datatype              string    `protobuf:"bytes,2,opt,name=datatype" json:"datatype,omitempty"`
	Username              string    `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Password              string    `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	SendOnboardingEmail   bool      `protobuf:"varint,5,opt,name=sendOnboardingEmail" json:"sendOnboardingEmail,omitempty"`
	OnboardingToken       string    `protobuf:"bytes,6,opt,name=onboardingToken" json:"onboardingToken,omitempty"`
	UserVerified          bool      `protobuf:"varint,7,opt,name=userVerified" json:"userVerified,omitempty"`
	State                 UserState `protobuf:"varint,8,opt,name=state,enum=gathergrpc.UserState" json:"state,omitempty"`
	Domains               []string  `protobuf:"bytes,9,rep,name=domains" json:"domains,omitempty"`
	CreatedTimestamp      int64     `protobuf:"varint,10,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp int64     `protobuf:"varint,11,opt,name=lastModifiedTimestamp" json:"lastModifiedTimestamp,omitempty"`
}

func (m *TenantUser) Reset()                    { *m = TenantUser{} }
func (m *TenantUser) String() string            { return proto.CompactTextString(m) }
func (*TenantUser) ProtoMessage()               {}
func (*TenantUser) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *TenantUser) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *TenantUser) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

func (m *TenantUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TenantUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TenantUser) GetSendOnboardingEmail() bool {
	if m != nil {
		return m.SendOnboardingEmail
	}
	return false
}

func (m *TenantUser) GetOnboardingToken() string {
	if m != nil {
		return m.OnboardingToken
	}
	return ""
}

func (m *TenantUser) GetUserVerified() bool {
	if m != nil {
		return m.UserVerified
	}
	return false
}

func (m *TenantUser) GetState() UserState {
	if m != nil {
		return m.State
	}
	return UserState_USER_UNKNOWN
}

func (m *TenantUser) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *TenantUser) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *TenantUser) GetLastModifiedTimestamp() int64 {
	if m != nil {
		return m.LastModifiedTimestamp
	}
	return 0
}

// TenantUserRequest - wrapper for requests that involve a User that
// is scoped to a single Tenant.
type TenantUserRequest struct {
	XId  string      `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string      `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *TenantUser `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *TenantUserRequest) Reset()                    { *m = TenantUserRequest{} }
func (m *TenantUserRequest) String() string            { return proto.CompactTextString(m) }
func (*TenantUserRequest) ProtoMessage()               {}
func (*TenantUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

func (m *TenantUserRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *TenantUserRequest) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *TenantUserRequest) GetData() *TenantUser {
	if m != nil {
		return m.Data
	}
	return nil
}

// TenantUserResponse - wrapper for responses to requests that involve a User that
// is scoped to a single Tenant.
type TenantUserResponse struct {
	XId  string      `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string      `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *TenantUser `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *TenantUserResponse) Reset()                    { *m = TenantUserResponse{} }
func (m *TenantUserResponse) String() string            { return proto.CompactTextString(m) }
func (*TenantUserResponse) ProtoMessage()               {}
func (*TenantUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

func (m *TenantUserResponse) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *TenantUserResponse) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *TenantUserResponse) GetData() *TenantUser {
	if m != nil {
		return m.Data
	}
	return nil
}

// TenantUserListResponse - a wrapper to handle requests that return a
// list of TenantUser objects.
type TenantUserListResponse struct {
	Data []*TenantUserResponse `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *TenantUserListResponse) Reset()                    { *m = TenantUserListResponse{} }
func (m *TenantUserListResponse) String() string            { return proto.CompactTextString(m) }
func (*TenantUserListResponse) ProtoMessage()               {}
func (*TenantUserListResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{20} }

func (m *TenantUserListResponse) GetData() []*TenantUserResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

// TenantUserIdRequest - wrapper for requests that involve a Tenant User,
// but only require the userID to complete the request.
type TenantUserIdRequest struct {
	TenantId string `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
}

func (m *TenantUserIdRequest) Reset()                    { *m = TenantUserIdRequest{} }
func (m *TenantUserIdRequest) String() string            { return proto.CompactTextString(m) }
func (*TenantUserIdRequest) ProtoMessage()               {}
func (*TenantUserIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{21} }

func (m *TenantUserIdRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *TenantUserIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// MonitoredObject - describes a unique device/object which is reporting
// data from the network.
type MonitoredObject struct {
	Id                    string                              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TenantId              string                              `protobuf:"bytes,2,opt,name=tenantId" json:"tenantId,omitempty"`
	Datatype              string                              `protobuf:"bytes,3,opt,name=datatype" json:"datatype,omitempty"`
	ActuatorType          MonitoredObject_DeviceType          `protobuf:"varint,4,opt,name=actuatorType,enum=gathergrpc.MonitoredObject_DeviceType" json:"actuatorType,omitempty"`
	ActuatorName          string                              `protobuf:"bytes,5,opt,name=actuatorName" json:"actuatorName,omitempty"`
	ReflectorType         MonitoredObject_DeviceType          `protobuf:"varint,6,opt,name=reflectorType,enum=gathergrpc.MonitoredObject_DeviceType" json:"reflectorType,omitempty"`
	ReflectorName         string                              `protobuf:"bytes,7,opt,name=reflectorName" json:"reflectorName,omitempty"`
	ObjectName            string                              `protobuf:"bytes,8,opt,name=objectName" json:"objectName,omitempty"`
	ObjectType            MonitoredObject_MonitoredObjectType `protobuf:"varint,9,opt,name=objectType,enum=gathergrpc.MonitoredObject_MonitoredObjectType" json:"objectType,omitempty"`
	CreatedTimestamp      int64                               `protobuf:"varint,10,opt,name=createdTimestamp" json:"createdTimestamp,omitempty"`
	LastModifiedTimestamp int64                               `protobuf:"varint,11,opt,name=lastModifiedTimestamp" json:"lastModifiedTimestamp,omitempty"`
	DomainSet             []string                            `protobuf:"bytes,12,rep,name=domainSet" json:"domainSet,omitempty"`
}

func (m *MonitoredObject) Reset()                    { *m = MonitoredObject{} }
func (m *MonitoredObject) String() string            { return proto.CompactTextString(m) }
func (*MonitoredObject) ProtoMessage()               {}
func (*MonitoredObject) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{22} }

func (m *MonitoredObject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MonitoredObject) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *MonitoredObject) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

func (m *MonitoredObject) GetActuatorType() MonitoredObject_DeviceType {
	if m != nil {
		return m.ActuatorType
	}
	return MonitoredObject_DT_UNKNOWN
}

func (m *MonitoredObject) GetActuatorName() string {
	if m != nil {
		return m.ActuatorName
	}
	return ""
}

func (m *MonitoredObject) GetReflectorType() MonitoredObject_DeviceType {
	if m != nil {
		return m.ReflectorType
	}
	return MonitoredObject_DT_UNKNOWN
}

func (m *MonitoredObject) GetReflectorName() string {
	if m != nil {
		return m.ReflectorName
	}
	return ""
}

func (m *MonitoredObject) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *MonitoredObject) GetObjectType() MonitoredObject_MonitoredObjectType {
	if m != nil {
		return m.ObjectType
	}
	return MonitoredObject_MO_UNKNOWN
}

func (m *MonitoredObject) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *MonitoredObject) GetLastModifiedTimestamp() int64 {
	if m != nil {
		return m.LastModifiedTimestamp
	}
	return 0
}

func (m *MonitoredObject) GetDomainSet() []string {
	if m != nil {
		return m.DomainSet
	}
	return nil
}

// MonitoredObjectRequest - Wrapper for requests involving a MonitoredObject that are
// scoped to a single Tenant.
type MonitoredObjectRequest struct {
	XId  string           `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string           `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *MonitoredObject `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *MonitoredObjectRequest) Reset()                    { *m = MonitoredObjectRequest{} }
func (m *MonitoredObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*MonitoredObjectRequest) ProtoMessage()               {}
func (*MonitoredObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{23} }

func (m *MonitoredObjectRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *MonitoredObjectRequest) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *MonitoredObjectRequest) GetData() *MonitoredObject {
	if m != nil {
		return m.Data
	}
	return nil
}

// MonitoredObjectRequest - Wrapper for responses involving a MonitoredObject that are
// scoped to a single Tenant.
type MonitoredObjectResponse struct {
	XId  string           `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	XRev string           `protobuf:"bytes,2,opt,name=_rev,json=Rev" json:"_rev,omitempty"`
	Data *MonitoredObject `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *MonitoredObjectResponse) Reset()                    { *m = MonitoredObjectResponse{} }
func (m *MonitoredObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*MonitoredObjectResponse) ProtoMessage()               {}
func (*MonitoredObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{24} }

func (m *MonitoredObjectResponse) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *MonitoredObjectResponse) GetXRev() string {
	if m != nil {
		return m.XRev
	}
	return ""
}

func (m *MonitoredObjectResponse) GetData() *MonitoredObject {
	if m != nil {
		return m.Data
	}
	return nil
}

// MonitoredObjectListResponse - Wrapper for requests which return a list of MonitoredObjects
// scoped to a single Tenant.
type MonitoredObjectListResponse struct {
	Data []*MonitoredObjectResponse `protobuf:"bytes,3,rep,name=data" json:"data,omitempty"`
}

func (m *MonitoredObjectListResponse) Reset()                    { *m = MonitoredObjectListResponse{} }
func (m *MonitoredObjectListResponse) String() string            { return proto.CompactTextString(m) }
func (*MonitoredObjectListResponse) ProtoMessage()               {}
func (*MonitoredObjectListResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{25} }

func (m *MonitoredObjectListResponse) GetData() []*MonitoredObjectResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type MonitoredObjectIdRequest struct {
	TenantId          string `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	MonitoredObjectId string `protobuf:"bytes,2,opt,name=monitoredObjectId" json:"monitoredObjectId,omitempty"`
}

func (m *MonitoredObjectIdRequest) Reset()                    { *m = MonitoredObjectIdRequest{} }
func (m *MonitoredObjectIdRequest) String() string            { return proto.CompactTextString(m) }
func (*MonitoredObjectIdRequest) ProtoMessage()               {}
func (*MonitoredObjectIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{26} }

func (m *MonitoredObjectIdRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *MonitoredObjectIdRequest) GetMonitoredObjectId() string {
	if m != nil {
		return m.MonitoredObjectId
	}
	return ""
}

// Provides options to configure how the GetMonitoredObjectToDomainMap API will return its results.
// byCount: true will return a count of Monitored Objects, false will return a set of MonitoredObject IDs.
// domainSet: set of Domain IDs to filter the request by.
type MonitoredObjectCountByDomainRequest struct {
	TenantId  string   `protobuf:"bytes,1,opt,name=tenantId" json:"tenantId,omitempty"`
	ByCount   bool     `protobuf:"varint,2,opt,name=byCount" json:"byCount,omitempty"`
	DomainSet []string `protobuf:"bytes,3,rep,name=domainSet" json:"domainSet,omitempty"`
}

func (m *MonitoredObjectCountByDomainRequest) Reset()         { *m = MonitoredObjectCountByDomainRequest{} }
func (m *MonitoredObjectCountByDomainRequest) String() string { return proto.CompactTextString(m) }
func (*MonitoredObjectCountByDomainRequest) ProtoMessage()    {}
func (*MonitoredObjectCountByDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{27}
}

func (m *MonitoredObjectCountByDomainRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *MonitoredObjectCountByDomainRequest) GetByCount() bool {
	if m != nil {
		return m.ByCount
	}
	return false
}

func (m *MonitoredObjectCountByDomainRequest) GetDomainSet() []string {
	if m != nil {
		return m.DomainSet
	}
	return nil
}

type MonitoredObjectCountByDomainResponse struct {
	DomainToMonitoredObjectCountMap map[string]int64                `protobuf:"bytes,1,rep,name=domainToMonitoredObjectCountMap" json:"domainToMonitoredObjectCountMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DomainToMonitoredObjectSetMap   map[string]*MonitoredObjectList `protobuf:"bytes,2,rep,name=domainToMonitoredObjectSetMap" json:"domainToMonitoredObjectSetMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MonitoredObjectCountByDomainResponse) Reset()         { *m = MonitoredObjectCountByDomainResponse{} }
func (m *MonitoredObjectCountByDomainResponse) String() string { return proto.CompactTextString(m) }
func (*MonitoredObjectCountByDomainResponse) ProtoMessage()    {}
func (*MonitoredObjectCountByDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{28}
}

func (m *MonitoredObjectCountByDomainResponse) GetDomainToMonitoredObjectCountMap() map[string]int64 {
	if m != nil {
		return m.DomainToMonitoredObjectCountMap
	}
	return nil
}

func (m *MonitoredObjectCountByDomainResponse) GetDomainToMonitoredObjectSetMap() map[string]*MonitoredObjectList {
	if m != nil {
		return m.DomainToMonitoredObjectSetMap
	}
	return nil
}

type MonitoredObjectList struct {
	MonitoredObjectSet []string `protobuf:"bytes,1,rep,name=monitoredObjectSet" json:"monitoredObjectSet,omitempty"`
}

func (m *MonitoredObjectList) Reset()                    { *m = MonitoredObjectList{} }
func (m *MonitoredObjectList) String() string            { return proto.CompactTextString(m) }
func (*MonitoredObjectList) ProtoMessage()               {}
func (*MonitoredObjectList) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{29} }

func (m *MonitoredObjectList) GetMonitoredObjectSet() []string {
	if m != nil {
		return m.MonitoredObjectSet
	}
	return nil
}

func init() {
	proto.RegisterType((*TenantDomain)(nil), "gathergrpc.TenantDomain")
	proto.RegisterType((*TenantDomainRequest)(nil), "gathergrpc.TenantDomainRequest")
	proto.RegisterType((*TenantDomainResponse)(nil), "gathergrpc.TenantDomainResponse")
	proto.RegisterType((*TenantDomainListResponse)(nil), "gathergrpc.TenantDomainListResponse")
	proto.RegisterType((*TenantDomainIdRequest)(nil), "gathergrpc.TenantDomainIdRequest")
	proto.RegisterType((*TenantIngestionProfile)(nil), "gathergrpc.TenantIngestionProfile")
	proto.RegisterType((*TenantIngestionProfile_MetricMap)(nil), "gathergrpc.TenantIngestionProfile.MetricMap")
	proto.RegisterType((*TenantIngestionProfile_MonitoredObjectMap)(nil), "gathergrpc.TenantIngestionProfile.MonitoredObjectMap")
	proto.RegisterType((*TenantIngestionProfileRequest)(nil), "gathergrpc.TenantIngestionProfileRequest")
	proto.RegisterType((*TenantIngestionProfileResponse)(nil), "gathergrpc.TenantIngestionProfileResponse")
	proto.RegisterType((*TenantIngestionProfileIdRequest)(nil), "gathergrpc.TenantIngestionProfileIdRequest")
	proto.RegisterType((*TenantThresholdProfile)(nil), "gathergrpc.TenantThresholdProfile")
	proto.RegisterType((*TenantThreshold)(nil), "gathergrpc.TenantThreshold")
	proto.RegisterType((*TenantMetric)(nil), "gathergrpc.TenantMetric")
	proto.RegisterType((*TenantMetricData)(nil), "gathergrpc.TenantMetricData")
	proto.RegisterType((*TenantEvent)(nil), "gathergrpc.TenantEvent")
	proto.RegisterType((*TenantThresholdProfileRequest)(nil), "gathergrpc.TenantThresholdProfileRequest")
	proto.RegisterType((*TenantThresholdProfileResponse)(nil), "gathergrpc.TenantThresholdProfileResponse")
	proto.RegisterType((*TenantThresholdProfileIdRequest)(nil), "gathergrpc.TenantThresholdProfileIdRequest")
	proto.RegisterType((*TenantUser)(nil), "gathergrpc.TenantUser")
	proto.RegisterType((*TenantUserRequest)(nil), "gathergrpc.TenantUserRequest")
	proto.RegisterType((*TenantUserResponse)(nil), "gathergrpc.TenantUserResponse")
	proto.RegisterType((*TenantUserListResponse)(nil), "gathergrpc.TenantUserListResponse")
	proto.RegisterType((*TenantUserIdRequest)(nil), "gathergrpc.TenantUserIdRequest")
	proto.RegisterType((*MonitoredObject)(nil), "gathergrpc.MonitoredObject")
	proto.RegisterType((*MonitoredObjectRequest)(nil), "gathergrpc.MonitoredObjectRequest")
	proto.RegisterType((*MonitoredObjectResponse)(nil), "gathergrpc.MonitoredObjectResponse")
	proto.RegisterType((*MonitoredObjectListResponse)(nil), "gathergrpc.MonitoredObjectListResponse")
	proto.RegisterType((*MonitoredObjectIdRequest)(nil), "gathergrpc.MonitoredObjectIdRequest")
	proto.RegisterType((*MonitoredObjectCountByDomainRequest)(nil), "gathergrpc.MonitoredObjectCountByDomainRequest")
	proto.RegisterType((*MonitoredObjectCountByDomainResponse)(nil), "gathergrpc.MonitoredObjectCountByDomainResponse")
	proto.RegisterType((*MonitoredObjectList)(nil), "gathergrpc.MonitoredObjectList")
	proto.RegisterEnum("gathergrpc.MonitoredObject_MonitoredObjectType", MonitoredObject_MonitoredObjectType_name, MonitoredObject_MonitoredObjectType_value)
	proto.RegisterEnum("gathergrpc.MonitoredObject_DeviceType", MonitoredObject_DeviceType_name, MonitoredObject_DeviceType_value)
}

func init() { proto.RegisterFile("gathergrpc/tenantModels.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 1388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0xff, 0x53, 0x94, 0x64, 0x6b, 0xec, 0xd8, 0xf2, 0x26, 0x71, 0x08, 0xe5, 0x4b, 0x60, 0x82,
	0x3f, 0x8c, 0x34, 0x90, 0x03, 0x37, 0x69, 0x8b, 0xa6, 0x17, 0x27, 0xf2, 0x41, 0x4d, 0x64, 0x1b,
	0xb4, 0x92, 0xa0, 0x27, 0x83, 0x16, 0x37, 0x36, 0x1b, 0x91, 0xab, 0x90, 0x2b, 0x07, 0x42, 0xdb,
	0x5b, 0x0f, 0x7d, 0x85, 0x9e, 0x0a, 0xf4, 0xe3, 0xd4, 0x27, 0xe8, 0x53, 0xf5, 0x15, 0x8a, 0xfd,
	0xa0, 0xb8, 0xfc, 0x10, 0x2d, 0x1a, 0xc9, 0x4d, 0x3b, 0x33, 0x3b, 0xbf, 0x99, 0xe1, 0xcc, 0x6f,
	0x77, 0x05, 0xb7, 0x4f, 0x6d, 0x7a, 0x86, 0x83, 0xd3, 0x60, 0x3c, 0xdc, 0xa6, 0xd8, 0xb7, 0x7d,
	0xda, 0x27, 0x0e, 0x1e, 0x85, 0x9d, 0x71, 0x40, 0x28, 0x41, 0x10, 0xab, 0x5b, 0xaa, 0xe9, 0x90,
	0x78, 0x1e, 0xf1, 0x55, 0x53, 0xf3, 0xe7, 0x0a, 0xac, 0x0e, 0xb8, 0x87, 0x2e, 0xf1, 0x6c, 0xd7,
	0x47, 0x2d, 0x58, 0x16, 0x1e, 0x7b, 0x8e, 0xa1, 0xb5, 0xb5, 0xad, 0x86, 0x35, 0x5b, 0x33, 0x9d,
	0x63, 0x53, 0x9b, 0x4e, 0xc7, 0xd8, 0xa8, 0x08, 0x5d, 0xb4, 0x46, 0x08, 0xaa, 0xbe, 0xed, 0x61,
	0x43, 0xe7, 0x72, 0xfe, 0x1b, 0x5d, 0x83, 0xda, 0x90, 0x8c, 0x48, 0x60, 0x54, 0xb9, 0x50, 0x2c,
	0xd0, 0x03, 0x68, 0x0e, 0x03, 0x6c, 0x53, 0xec, 0x0c, 0x5c, 0x0f, 0x87, 0xd4, 0xf6, 0xc6, 0x46,
	0xad, 0xad, 0x6d, 0xe9, 0x56, 0x46, 0x8e, 0x1e, 0xc3, 0xf5, 0x91, 0x1d, 0xb2, 0xec, 0xdc, 0xb7,
	0xae, 0xba, 0xa1, 0xce, 0x37, 0xe4, 0x2b, 0xd1, 0x23, 0xb8, 0x4a, 0xcf, 0x02, 0x1c, 0x9e, 0x91,
	0x91, 0x73, 0x18, 0x90, 0xb7, 0xee, 0x08, 0x1f, 0x61, 0x6a, 0x2c, 0xb5, 0xf5, 0xad, 0x86, 0x95,
	0xa7, 0x32, 0x4f, 0xe1, 0xaa, 0x5a, 0x05, 0x0b, 0xbf, 0x9f, 0xe0, 0x90, 0xa2, 0x75, 0xd0, 0x8f,
	0xdd, 0xa8, 0x0e, 0x95, 0x9e, 0x83, 0x36, 0xa0, 0x7a, 0x1c, 0xe0, 0x73, 0x99, 0xbd, 0x6e, 0xe1,
	0x73, 0xf4, 0x10, 0xaa, 0xac, 0x08, 0x3c, 0xf1, 0x95, 0x1d, 0xa3, 0x13, 0xd7, 0xbb, 0x93, 0x70,
	0xc9, 0xad, 0xcc, 0x33, 0xb8, 0x96, 0x04, 0x0a, 0xc7, 0xc4, 0x0f, 0xf1, 0x27, 0x40, 0x3a, 0x04,
	0x43, 0x95, 0xbe, 0x74, 0x43, 0x3a, 0x43, 0x7b, 0x2c, 0x3d, 0x69, 0x6d, 0x7d, 0x6b, 0x65, 0xa7,
	0x3d, 0xd7, 0x93, 0xb4, 0x97, 0x1e, 0x0f, 0xe0, 0xba, 0xaa, 0xed, 0x39, 0x51, 0x99, 0x2e, 0xea,
	0x19, 0x69, 0x3e, 0xeb, 0x19, 0xb9, 0x36, 0x7f, 0xaf, 0xc3, 0xa6, 0xf0, 0xd8, 0xf3, 0x4f, 0x71,
	0x48, 0x5d, 0xe2, 0xcb, 0x6f, 0x72, 0xe9, 0x36, 0xec, 0xc1, 0x92, 0x87, 0x69, 0xe0, 0x0e, 0x43,
	0x43, 0xe7, 0xc9, 0x6d, 0x67, 0x93, 0x4b, 0x83, 0x75, 0xfa, 0x62, 0xc7, 0x9e, 0x4f, 0x83, 0xa9,
	0x15, 0xed, 0xcf, 0xed, 0xd3, 0x6a, 0xd9, 0x3e, 0xad, 0x15, 0xf4, 0x69, 0xeb, 0x4f, 0x0d, 0x1a,
	0x02, 0xbb, 0x6f, 0x8f, 0xd1, 0x77, 0xd0, 0xf0, 0xa2, 0x85, 0xfc, 0x32, 0x4f, 0x17, 0x0e, 0xbe,
	0x6f, 0x8f, 0xe3, 0x5f, 0x22, 0x91, 0xd8, 0x5b, 0xeb, 0x1b, 0x58, 0x4b, 0x2a, 0x51, 0x13, 0xf4,
	0x77, 0x78, 0x2a, 0x4b, 0xcb, 0x7e, 0xb2, 0x61, 0x3d, 0xb7, 0x47, 0x13, 0x51, 0xd2, 0x65, 0x4b,
	0x2c, 0xbe, 0xae, 0x7c, 0xa5, 0xb5, 0x7e, 0xa9, 0x00, 0xea, 0x13, 0xdf, 0xa5, 0x24, 0xc0, 0xce,
	0xc1, 0xc9, 0xf7, 0x78, 0x48, 0x59, 0xbc, 0x3f, 0x01, 0xf2, 0x32, 0x52, 0x19, 0x78, 0x7f, 0x91,
	0xc0, 0x33, 0x9b, 0x73, 0x44, 0x22, 0x95, 0x1c, 0xa0, 0x56, 0x08, 0x37, 0xe6, 0x98, 0xe7, 0x24,
	0xf7, 0x4c, 0x4d, 0x6e, 0x65, 0xe7, 0x61, 0x99, 0xba, 0xaa, 0xa5, 0x78, 0x0f, 0xab, 0x6a, 0xb3,
	0xe4, 0x20, 0xbd, 0x48, 0x22, 0x3d, 0xb9, 0x54, 0x21, 0x14, 0x48, 0xf3, 0x07, 0xb8, 0x9d, 0xbf,
	0xaf, 0x0c, 0x49, 0x7d, 0x91, 0xa0, 0x0e, 0xf3, 0xe2, 0xa0, 0xe4, 0xc8, 0xff, 0x08, 0x77, 0xe6,
	0x81, 0x97, 0x20, 0xae, 0xcb, 0xa2, 0x7b, 0x70, 0x37, 0x5f, 0xbf, 0x18, 0xf5, 0x74, 0x00, 0xb9,
	0x99, 0x8d, 0x32, 0xae, 0x1c, 0x8d, 0xf9, 0xaf, 0x16, 0xd1, 0xd1, 0x20, 0x75, 0x44, 0x5c, 0x9a,
	0x8e, 0x9e, 0x02, 0xcc, 0x8e, 0x9b, 0x88, 0x91, 0x6e, 0x66, 0xf3, 0x9f, 0xe1, 0x59, 0x8a, 0xf9,
	0xa7, 0x27, 0x20, 0x13, 0xc3, 0x7a, 0x2a, 0x00, 0xb4, 0x13, 0x13, 0xa8, 0x18, 0xe5, 0x9c, 0x73,
	0x46, 0x8c, 0x40, 0xcc, 0x94, 0x77, 0x00, 0x08, 0x6f, 0xdd, 0x41, 0x5c, 0x03, 0x45, 0x62, 0x1e,
	0x46, 0x77, 0x0c, 0xb1, 0x11, 0xad, 0x41, 0x25, 0x6e, 0x19, 0xd7, 0x41, 0x8f, 0x64, 0x7f, 0x54,
	0x38, 0xe0, 0xad, 0x79, 0x80, 0x5d, 0x9b, 0xda, 0xb2, 0x33, 0x6c, 0x68, 0xa6, 0x35, 0xe8, 0x16,
	0x34, 0x1c, 0x37, 0xc0, 0x43, 0xf6, 0x51, 0xa5, 0xf3, 0x58, 0x80, 0xb6, 0xa1, 0x8e, 0xcf, 0xb1,
	0x4f, 0x43, 0x89, 0x72, 0x23, 0x8b, 0xb2, 0xc7, 0xf4, 0x96, 0x34, 0x33, 0xff, 0xd1, 0x60, 0x45,
	0x91, 0xb3, 0x0b, 0xce, 0xc4, 0x77, 0xa9, 0xf4, 0xcc, 0x7f, 0x33, 0x99, 0xf2, 0xd9, 0xf9, 0x6f,
	0x56, 0x8c, 0xc9, 0x78, 0x8c, 0x83, 0x67, 0x64, 0xe2, 0x3b, 0xbc, 0xe5, 0x2b, 0x96, 0x22, 0x61,
	0xfa, 0x11, 0xf9, 0x10, 0xe9, 0xab, 0x42, 0x1f, 0x4b, 0x50, 0x1b, 0x56, 0xb8, 0xf5, 0x11, 0x4b,
	0x8c, 0xf2, 0xef, 0xb7, 0x6c, 0xa9, 0x22, 0x66, 0xc1, 0xed, 0xa5, 0x45, 0x5d, 0x58, 0x28, 0xa2,
	0x98, 0x33, 0xd2, 0x8d, 0xfc, 0x51, 0x39, 0x23, 0xe3, 0x3c, 0xc5, 0x19, 0x59, 0xf0, 0x8f, 0xc9,
	0x19, 0x73, 0xd0, 0x67, 0x9c, 0x91, 0xd6, 0x2f, 0xcc, 0x19, 0x34, 0xb3, 0x31, 0xe2, 0x8c, 0xac,
	0xc6, 0xfc, 0x4b, 0x07, 0x10, 0x78, 0xaf, 0x42, 0x1c, 0x5c, 0x9a, 0x27, 0x5a, 0xb0, 0x3c, 0x09,
	0x71, 0xa0, 0xdc, 0xa0, 0x67, 0x6b, 0xa6, 0x1b, 0xdb, 0x61, 0xf8, 0x81, 0x04, 0x8e, 0xbc, 0x48,
	0xcf, 0xd6, 0xec, 0xa6, 0x1b, 0x62, 0xdf, 0x39, 0xf0, 0x4f, 0x88, 0x1d, 0x38, 0xae, 0x7f, 0xba,
	0xe7, 0xd9, 0xee, 0x48, 0x36, 0x4d, 0x9e, 0x0a, 0x6d, 0xc1, 0x3a, 0x99, 0x89, 0x06, 0xe4, 0x1d,
	0xf6, 0x79, 0x03, 0x35, 0xac, 0xb4, 0x18, 0x99, 0xb0, 0xca, 0x62, 0x78, 0x8d, 0x03, 0xce, 0x1a,
	0xc6, 0x12, 0x77, 0x9a, 0x90, 0xa1, 0xcf, 0xa0, 0x16, 0x52, 0x9b, 0x62, 0x63, 0xb9, 0xad, 0x6d,
	0xad, 0xed, 0x5c, 0x57, 0x3f, 0x13, 0x2b, 0xc8, 0x11, 0x53, 0x5a, 0xc2, 0x06, 0x19, 0xb0, 0x24,
	0xae, 0x7e, 0xa1, 0xd1, 0xe0, 0x57, 0xf1, 0x68, 0x99, 0xcb, 0x74, 0x50, 0x96, 0xe9, 0x56, 0x8a,
	0x98, 0x6e, 0x08, 0x1b, 0xf1, 0x67, 0x2a, 0x33, 0x05, 0x0f, 0x12, 0x7d, 0xb8, 0x99, 0xed, 0x43,
	0xee, 0x50, 0xf4, 0x9e, 0x03, 0x48, 0x05, 0x29, 0xd1, 0xed, 0x65, 0x50, 0x5e, 0x46, 0xa7, 0x14,
	0x93, 0x25, 0xae, 0xf5, 0x3b, 0x89, 0x6b, 0xfd, 0x9d, 0x39, 0x5e, 0x92, 0x97, 0xfa, 0x5e, 0xf4,
	0xf2, 0x61, 0xba, 0xc5, 0x66, 0x64, 0x13, 0xea, 0x13, 0x6e, 0x2c, 0x33, 0x90, 0x2b, 0xf3, 0x8f,
	0x1a, 0xac, 0xa7, 0xee, 0x32, 0x19, 0xaa, 0x57, 0xfd, 0x56, 0x0a, 0x06, 0x44, 0x4f, 0x0d, 0xc8,
	0xb7, 0xb0, 0x6a, 0x0f, 0xe9, 0xc4, 0xa6, 0x24, 0xe0, 0x87, 0x4c, 0x95, 0xf7, 0xdb, 0xff, 0xd5,
	0x14, 0x53, 0xd0, 0x9d, 0x2e, 0x3e, 0x77, 0x87, 0x98, 0x59, 0x5b, 0x89, 0xbd, 0xac, 0xb1, 0xa3,
	0xf5, 0x3e, 0x1b, 0xb8, 0x1a, 0xc7, 0x4a, 0xc8, 0xd0, 0x4b, 0xb8, 0x12, 0xe0, 0xb7, 0x23, 0x3c,
	0x8c, 0x00, 0xeb, 0xa5, 0x00, 0x93, 0x9b, 0xd1, 0x7d, 0xc5, 0x1b, 0x87, 0x5c, 0xe2, 0x90, 0x49,
	0x61, 0x7c, 0x8c, 0x72, 0x93, 0x65, 0xf5, 0x18, 0xe5, 0xfa, 0x83, 0xc4, 0x31, 0xdb, 0xe0, 0x01,
	0x6d, 0x17, 0x05, 0x94, 0x5a, 0xf3, 0xc8, 0x14, 0x17, 0x9f, 0x7e, 0xec, 0xf8, 0x99, 0xcc, 0x67,
	0x9c, 0xbd, 0xbf, 0x57, 0xf9, 0xd0, 0xc7, 0x02, 0xf3, 0x11, 0x5c, 0xcd, 0x09, 0x11, 0xad, 0x01,
	0xf4, 0x0f, 0x8e, 0x5f, 0xed, 0xbf, 0xd8, 0x3f, 0x78, 0xb3, 0xdf, 0xfc, 0x1f, 0x6a, 0x40, 0x6d,
	0xf0, 0x66, 0xb7, 0x7f, 0xd8, 0xd4, 0xcc, 0x5d, 0x80, 0xb8, 0xca, 0xcc, 0xb0, 0x3b, 0x50, 0x0c,
	0x9b, 0xb0, 0xba, 0xfb, 0xfc, 0xf9, 0x5e, 0xb7, 0xb7, 0xbb, 0x7f, 0xbc, 0xdf, 0xeb, 0x36, 0x35,
	0xb4, 0x01, 0x57, 0x66, 0x92, 0xd7, 0x4c, 0x54, 0x31, 0x3d, 0xd8, 0x4c, 0x81, 0x96, 0xa1, 0x83,
	0xed, 0xc4, 0xa0, 0xde, 0x2c, 0xa8, 0xbe, 0x9c, 0x2f, 0x3f, 0xf3, 0x4c, 0x29, 0x45, 0x0c, 0xa5,
	0xf1, 0x5e, 0xc3, 0xcd, 0x94, 0x22, 0x41, 0x11, 0x5f, 0xce, 0xfc, 0x31, 0x8a, 0xb8, 0x57, 0xe4,
	0x2f, 0xc9, 0x13, 0x0e, 0x18, 0x29, 0x83, 0xc5, 0xc8, 0xe2, 0x21, 0x6c, 0x78, 0xe9, 0x7d, 0x32,
	0xc1, 0xac, 0xc2, 0x9c, 0xc2, 0xbd, 0x14, 0xca, 0x73, 0x32, 0xf1, 0xe9, 0xb3, 0x69, 0xf2, 0x7f,
	0x99, 0x22, 0x40, 0x03, 0x96, 0x4e, 0xa6, 0x7c, 0x97, 0x7c, 0xc9, 0x46, 0xcb, 0x64, 0x33, 0xea,
	0xe9, 0x66, 0xfc, 0xbb, 0x0a, 0xf7, 0x8b, 0xb1, 0x65, 0x09, 0x7f, 0xd3, 0xe0, 0xae, 0xd8, 0x36,
	0x20, 0x79, 0x1b, 0xe2, 0x57, 0xf0, 0xab, 0x82, 0xf2, 0xe6, 0xfa, 0xee, 0x74, 0x8b, 0xfd, 0x8a,
	0xd7, 0xf0, 0x45, 0xe8, 0xe8, 0x57, 0x0d, 0x6e, 0xcf, 0xb1, 0x39, 0xc2, 0x3c, 0x3e, 0x71, 0x07,
	0x3e, 0xfa, 0x58, 0xf1, 0x09, 0xaf, 0x22, 0xba, 0x62, 0xe4, 0x96, 0x05, 0xf7, 0x17, 0x49, 0xf2,
	0xa2, 0x3f, 0x28, 0xf4, 0xe4, 0xab, 0xdc, 0xbc, 0x38, 0xb0, 0x1c, 0x8f, 0x4f, 0x92, 0x6f, 0xf5,
	0xbb, 0x05, 0xe5, 0xe0, 0x43, 0xa4, 0xbc, 0xca, 0xf7, 0x32, 0xd4, 0xc5, 0x2c, 0xd8, 0xf5, 0xd1,
	0xcb, 0x44, 0xc0, 0xbb, 0xa1, 0x61, 0xe5, 0x68, 0x4e, 0xea, 0xfc, 0x5f, 0xd8, 0xcf, 0xff, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0xd7, 0x1b, 0x41, 0x71, 0xd1, 0x15, 0x00, 0x00,
}
