// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	swagmodels "github.com/accedian/adh-gather/swagmodels"
)

// CreateTenantUserOKCode is the HTTP code returned for type CreateTenantUserOK
const CreateTenantUserOKCode int = 200

/*CreateTenantUserOK create tenant user o k

swagger:response createTenantUserOK
*/
type CreateTenantUserOK struct {

	/*
	  In: Body
	*/
	Payload *swagmodels.JSONAPITenantUser `json:"body,omitempty"`
}

// NewCreateTenantUserOK creates CreateTenantUserOK with default headers values
func NewCreateTenantUserOK() *CreateTenantUserOK {

	return &CreateTenantUserOK{}
}

// WithPayload adds the payload to the create tenant user o k response
func (o *CreateTenantUserOK) WithPayload(payload *swagmodels.JSONAPITenantUser) *CreateTenantUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create tenant user o k response
func (o *CreateTenantUserOK) SetPayload(payload *swagmodels.JSONAPITenantUser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTenantUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateTenantUserBadRequestCode is the HTTP code returned for type CreateTenantUserBadRequest
const CreateTenantUserBadRequestCode int = 400

/*CreateTenantUserBadRequest Request data does not pass validation

swagger:response createTenantUserBadRequest
*/
type CreateTenantUserBadRequest struct {
}

// NewCreateTenantUserBadRequest creates CreateTenantUserBadRequest with default headers values
func NewCreateTenantUserBadRequest() *CreateTenantUserBadRequest {

	return &CreateTenantUserBadRequest{}
}

// WriteResponse to the client
func (o *CreateTenantUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateTenantUserInternalServerErrorCode is the HTTP code returned for type CreateTenantUserInternalServerError
const CreateTenantUserInternalServerErrorCode int = 500

/*CreateTenantUserInternalServerError Unexpected error processing request

swagger:response createTenantUserInternalServerError
*/
type CreateTenantUserInternalServerError struct {
}

// NewCreateTenantUserInternalServerError creates CreateTenantUserInternalServerError with default headers values
func NewCreateTenantUserInternalServerError() *CreateTenantUserInternalServerError {

	return &CreateTenantUserInternalServerError{}
}

// WriteResponse to the client
func (o *CreateTenantUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
