// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	swagmodels "github.com/accedian/adh-gather/swagmodels"
)

// GetAllTenantThresholdProfilesOKCode is the HTTP code returned for type GetAllTenantThresholdProfilesOK
const GetAllTenantThresholdProfilesOKCode int = 200

/*GetAllTenantThresholdProfilesOK get all tenant threshold profiles o k

swagger:response getAllTenantThresholdProfilesOK
*/
type GetAllTenantThresholdProfilesOK struct {

	/*
	  In: Body
	*/
	Payload *swagmodels.JSONAPITenantThresholdProfileList `json:"body,omitempty"`
}

// NewGetAllTenantThresholdProfilesOK creates GetAllTenantThresholdProfilesOK with default headers values
func NewGetAllTenantThresholdProfilesOK() *GetAllTenantThresholdProfilesOK {

	return &GetAllTenantThresholdProfilesOK{}
}

// WithPayload adds the payload to the get all tenant threshold profiles o k response
func (o *GetAllTenantThresholdProfilesOK) WithPayload(payload *swagmodels.JSONAPITenantThresholdProfileList) *GetAllTenantThresholdProfilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all tenant threshold profiles o k response
func (o *GetAllTenantThresholdProfilesOK) SetPayload(payload *swagmodels.JSONAPITenantThresholdProfileList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllTenantThresholdProfilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllTenantThresholdProfilesInternalServerErrorCode is the HTTP code returned for type GetAllTenantThresholdProfilesInternalServerError
const GetAllTenantThresholdProfilesInternalServerErrorCode int = 500

/*GetAllTenantThresholdProfilesInternalServerError Unexpected error processing request

swagger:response getAllTenantThresholdProfilesInternalServerError
*/
type GetAllTenantThresholdProfilesInternalServerError struct {
}

// NewGetAllTenantThresholdProfilesInternalServerError creates GetAllTenantThresholdProfilesInternalServerError with default headers values
func NewGetAllTenantThresholdProfilesInternalServerError() *GetAllTenantThresholdProfilesInternalServerError {

	return &GetAllTenantThresholdProfilesInternalServerError{}
}

// WriteResponse to the client
func (o *GetAllTenantThresholdProfilesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
