// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	swagmodels "github.com/accedian/adh-gather/swagmodels"
)

// UpdateTenantThresholdProfileOKCode is the HTTP code returned for type UpdateTenantThresholdProfileOK
const UpdateTenantThresholdProfileOKCode int = 200

/*UpdateTenantThresholdProfileOK update tenant threshold profile o k

swagger:response updateTenantThresholdProfileOK
*/
type UpdateTenantThresholdProfileOK struct {

	/*
	  In: Body
	*/
	Payload *swagmodels.JSONAPITenantThresholdProfile `json:"body,omitempty"`
}

// NewUpdateTenantThresholdProfileOK creates UpdateTenantThresholdProfileOK with default headers values
func NewUpdateTenantThresholdProfileOK() *UpdateTenantThresholdProfileOK {

	return &UpdateTenantThresholdProfileOK{}
}

// WithPayload adds the payload to the update tenant threshold profile o k response
func (o *UpdateTenantThresholdProfileOK) WithPayload(payload *swagmodels.JSONAPITenantThresholdProfile) *UpdateTenantThresholdProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update tenant threshold profile o k response
func (o *UpdateTenantThresholdProfileOK) SetPayload(payload *swagmodels.JSONAPITenantThresholdProfile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateTenantThresholdProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateTenantThresholdProfileBadRequestCode is the HTTP code returned for type UpdateTenantThresholdProfileBadRequest
const UpdateTenantThresholdProfileBadRequestCode int = 400

/*UpdateTenantThresholdProfileBadRequest Request data does not pass validation

swagger:response updateTenantThresholdProfileBadRequest
*/
type UpdateTenantThresholdProfileBadRequest struct {
}

// NewUpdateTenantThresholdProfileBadRequest creates UpdateTenantThresholdProfileBadRequest with default headers values
func NewUpdateTenantThresholdProfileBadRequest() *UpdateTenantThresholdProfileBadRequest {

	return &UpdateTenantThresholdProfileBadRequest{}
}

// WriteResponse to the client
func (o *UpdateTenantThresholdProfileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateTenantThresholdProfileInternalServerErrorCode is the HTTP code returned for type UpdateTenantThresholdProfileInternalServerError
const UpdateTenantThresholdProfileInternalServerErrorCode int = 500

/*UpdateTenantThresholdProfileInternalServerError Unexpected error processing request

swagger:response updateTenantThresholdProfileInternalServerError
*/
type UpdateTenantThresholdProfileInternalServerError struct {
}

// NewUpdateTenantThresholdProfileInternalServerError creates UpdateTenantThresholdProfileInternalServerError with default headers values
func NewUpdateTenantThresholdProfileInternalServerError() *UpdateTenantThresholdProfileInternalServerError {

	return &UpdateTenantThresholdProfileInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateTenantThresholdProfileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
