// Code generated by go-swagger; DO NOT EDIT.

package tenant_provisioning_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateReportScheduleConfigHandlerFunc turns a function with the right signature into a update report schedule config handler
type UpdateReportScheduleConfigHandlerFunc func(UpdateReportScheduleConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateReportScheduleConfigHandlerFunc) Handle(params UpdateReportScheduleConfigParams) middleware.Responder {
	return fn(params)
}

// UpdateReportScheduleConfigHandler interface for that can handle valid update report schedule config params
type UpdateReportScheduleConfigHandler interface {
	Handle(UpdateReportScheduleConfigParams) middleware.Responder
}

// NewUpdateReportScheduleConfig creates a new http.Handler for the update report schedule config operation
func NewUpdateReportScheduleConfig(ctx *middleware.Context, handler UpdateReportScheduleConfigHandler) *UpdateReportScheduleConfig {
	return &UpdateReportScheduleConfig{Context: ctx, Handler: handler}
}

/*UpdateReportScheduleConfig swagger:route PUT /v1/tenants/{tenantId}/report-schedule-configs TenantProvisioningService updateReportScheduleConfig

Update a report schedule configuration for a Tenant.

*/
type UpdateReportScheduleConfig struct {
	Context *middleware.Context
	Handler UpdateReportScheduleConfigHandler
}

func (o *UpdateReportScheduleConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateReportScheduleConfigParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
